### ISSUE TITLE
Search: ArticlePage results are returned in old->new order

### ISSUE THREAD

**Issue by vsalvino** [coderedcorp/coderedcms#101]
Ideally ArticlePage (or any other page type) that match the search query should be returned in the order specified by the parent page layout settings, or at a minimum newest to oldest as a better default.

**Comment by corysutyak** [comment]
I'm not sure the best way to go about this.  We can surely organize the list of returned results by `date_published` or something similar.  But if the default search backend is organizing based on relevancy, any sorting after the fact will no longer respect that relevancy.  The same is true if results are organized by model type.  We would probably have to write our own search backend and force the CMS to only use that backend.  That looks non-trivial and we would be preventing users from doing something they normally can do with Wagtail.

**Comment by corysutyak** [comment]
Fixed in PR #110
