### ISSUE TITLE
Form submissions showing UTC time

### ISSUE THREAD

**Issue by vsalvino** [coderedcorp/coderedcms#116]
Form submissions (Forms tab on left side bar) show the "Submission Date" in UTC time. Ideally this should render based on the timezone configured in the Django settings.

**Comment by vsalvino** [comment]
This could end up being a fix required in wagtail itself... further investigation is needed. Either way it would make for a nice pull request either here or to wagtail.

**Comment by hariAlokin** [comment]
I am also facing this issue, Is this fixable ?

**Comment by vsalvino** [comment]
This has been fixed in some recent version of wagtail (I think 2.15 or 2.16).
