### ISSUE TITLE
Prevent PDF's from being served as a download without specifying it as such.

### ISSUE THREAD

**Issue by corysutyak** [coderedcorp/coderedcms#16]
Currently, if you choose a document with a `DocumentChooserBlock` and serve the document, you will be forced to download it instead of viewing it in browser.  To fix this, you will probably want to use the `before_serve_document` hook https://docs.wagtail.io/en/v2.2.2/reference/hooks.html#document-serving to use our own response in the case of pdfs. https://stackoverflow.com/questions/47205668/wagtail-document-links-downloading-instead-of-displaying-as-a-page Might provide a good example.

**Comment by vsalvino** [comment]
This could probably be applied to all Documents. PDFs would be the primary use case, but I could see other file types that would want to trigger an application or browser plugin viewer.

Just make sure the download block continues to force download - it looks like the download achor attribute has pretty good browser support so I don't think this should be a problem.
