### ISSUE TITLE
RichTextBlock renders a redundant div

### ISSUE THREAD

**Issue by phyominh** [coderedcorp/coderedcms#164]
Rich text blocks create redundant div tags because [rich_text_block](https://github.com/coderedcorp/coderedcms/blob/master/coderedcms/templates/coderedcms/blocks/rich_text_block.html) extends from [base_block](https://github.com/coderedcorp/coderedcms/blob/master/coderedcms/templates/coderedcms/blocks/base_block.html) which I think is unnecessary.

**Comment by vsalvino** [comment]
You are right, our rich text block class does not actually inherit from BaseBlock, so the template should not either. Feel free to create a pull request fixing this!

**Comment by vsalvino** [comment]
Fixed in 0.14.1
