### ISSUE TITLE
Navigation Bar Snippets - External Links Not Displaying

### ISSUE THREAD

**Issue by tractcom** [coderedcorp/coderedcms#168]
External links do not display in the navbar when added in the relevant navigation bar snippet. The same seems to apply to document links.

**Comment by vsalvino** [comment]
Can you confirm what version of coderedcms you are using? I think this bug was introduced in version 0.12, and was fixed in version 0.14

**Comment by tractcom** [comment]
Ahhhh you are correct, upgrading sorted the problem. Apologies I had only recently deployed and started playing!! Will close this issue, sorry for wasting your time.
