### ISSUE TITLE
Unable to view Article pages in production[Community]

### ISSUE THREAD

**Issue by anthonygoslar** [coderedcorp/coderedcms#183]
**Describe the bug**
If you create an ArticleIndex page from the admin and begin it with the heading and hence slug "media", there's a url mismatch with the actual media folder.

**To Reproduce**
1. Go to 'Add a new page'
2. Click on 'Article Page'
3. Click create 'An Article Page'
4. Put 'media centre' as the heading
5. Publish it
6. See below for nginx output

If you use 'media-centre' as the slug, a 404 error is returned.
`2019/05/12 19:36:26 [error] 32300#32300: *661 "/src/media/-centre/index.html" is not found (2: No such file or directory), client: 100.100.100.100, server: 200.200.200.200, request: "GET /media-centre/ HTTP/1.1", host: "200.200.200.200"`

If you use 'media' as the slug, a 403 error is returned.
`2019/05/12 19:52:41 [error] 32300#32300: *762 "/src/media//article-3/index.html" is not found (2: No such file or directory), client: 100.100.100.100, server: 200.200.200.200, request: "GET /media/article-3/ HTTP/1.1", host: "200.200.200.200"`

**Expected behavior**
Go to the url with the correct slug

**Additional context**
If I use 'ArticleLanding' as the slug it works. It seems like some slugs should be blacklisted.

**Comment by vsalvino** [comment]
Very interesting find - thanks for reporting, I will look into it. A couple thoughts:
* I wonder if the behavior is the same when making a normal Wagtail `Page` with slug `media-centre`.
* Does the same issue happen on other page types or just on `ArticleIndexPage`?

**Comment by anthonygoslar** [comment]
I tested it with a normal Page model with the same result. As soon as I changed the slug to something else it displayed.

If I change the slug to 'media' the error goes from 404 to 403, indicating it's a URL issue. It only happens during production though, not on development. 

This leads me to think it's likely the nginx server settings pointing media to '/media/. If that is the case, an easy fix would be to change the MEDIA_ROOT folder and nginx setting.

**Comment by vsalvino** [comment]
In your nginx config, is the location for media specified with or without a slash? If it is specified **without** a slash, then that would probably be causing the error (e.g. `/media-centre` would then be triggered by NGINX).

The NGINX location should begin and end with a slash, e.g. `/media/`

**Comment by anthonygoslar** [comment]
That's it! Thanks very much. I'm really enjoying your CMS.
