### ISSUE TITLE
Specify language in base.html

### ISSUE THREAD

**Issue by hayleyhartman** [coderedcorp/coderedcms#195]
**Describe the bug**

**To Reproduce**
As is, this bug gets consistently reported for all CodeRed CMS sites when run through and ADA checker

**Expected behavior**
Setting language assists non-text readers to use a website:
"Language information assists speech synthesizers and Braille translators to produce usable results. These applications need to know whether they can produce output from the text, or whether perhaps they need to switch to a different language mode.

Language tagging is recommended by the W3C Web Accessibility Guidelines, which is enforced by governmental policies in some countries, eg. UK - Disability Discrimination Act (UK)."

**Comment by vsalvino** [comment]
Merged via #197
