### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by corysutyak** [coderedcorp/coderedcms#2]
Base level unit tests, ideally for:
-  Default project_template(make sure it works so we aren't generating a broken project)
-  Each block
-  Each page type (including forms)

More advanced things to test (for consideration): file blacklist/whitelist email functionality (not sure how to test this, but make sure any default emails get rendered without issue) custom admin functionality e.g. snippets, settings. HTML validity checker of generated pages * Accessibility tool checker of generated pages.

**Comment by corysutyak** [comment]
It's always good to meet others in the wagtail space!  In a vacuum, I really do prefer pytest over the TestCase.  However, the testing utilities that wagtail provides assumes you're using TestCase.  I would very much like to piggyback off of the groundwork already provided.  So I think we'll just go with the default.

**Comment by corysutyak** [comment]
Oh, I didn't know that.  I'll have to take another look then.

**Comment by vsalvino** [comment]
Merged via #179
