### ISSUE TITLE
Navbar and Footer snippets to not support multisite

### ISSUE THREAD

**Issue by vsalvino** [coderedcorp/coderedcms#202]
**Describe the bug**
All navbars and footers are rendered on the page, regardless of the site. We should be specifying the site from the request when querying navbars and footers.

https://github.com/coderedcorp/coderedcms/blob/a3ab4de00e043b22975c06bc5408e9fe2d3a9118/coderedcms/templatetags/coderedcms_tags.py#L81-L87

**To Reproduce**
1. Create multiple sites / root pages
2. Create a different navbar or footer snippet in each site.
3. When browsing each specific site, navbars/footers from both sites are rendered.

**Expected behavior**
Only navbars and footers for a specific site should render when browsing that site.

**Additional context**
See community issue #200

**Comment by carlosmonari** [comment]
Hi everybody,

I wrote a solution for this problem:

Is it possible put my solution in CodeRed CMS ?

I change, and test, my code for NavBar.

The solution is:

in file wagtailsettings_models.py (add after field favicon in class LayoutSettings )

    navbar_name = models.CharField(
        blank=True,
        max_length=50,
        verbose_name=_('Navbar name'),
        help_text=_('It is necessary to associate when you create a Navigation Bar fragments.'),
    )
		
and add panels


# before
    panels = [
        MultiFieldPanel(
            [
                ImageChooserPanel('logo'),
                ImageChooserPanel('favicon'),
            ],
            heading=_('Branding')
        ),
        MultiFieldPanel(
            [
                FieldPanel('navbar_color_scheme'),
                FieldPanel('navbar_class'),
				........
				
# after
    panels = [
        MultiFieldPanel(
            [
                ImageChooserPanel('logo'),
                ImageChooserPanel('favicon'),
            ],
            heading=_('Branding')
        ),
        MultiFieldPanel(
            [
                FieldPanel('navbar_name'),
                FieldPanel('navbar_color_scheme'),
                FieldPanel('navbar_class'),
				........

				
in file snippet_models.py (add after field name in class Navbar )				

# included 
from coderedcms.models.wagtailsettings_models import LayoutSettings

				
    layoutsetting = models.ForeignKey(
        LayoutSettings,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
        verbose_name=_('Layout Page'),
        help_text=_('The Layout page users to determinate a site owner Navigation Bar Manu.'),
    )


and increase panels

# before
    panels = [
        FieldPanel('name'),
        MultiFieldPanel(
            [
                FieldPanel('custom_css_class'),
                FieldPanel('custom_id'),
            ],
	..............

# after
    panels = [
        FieldPanel('name'),
        FieldPanel('layoutsetting'),
        MultiFieldPanel(
            [
                FieldPanel('custom_css_class'),
                FieldPanel('custom_id'),
            ],
		................
		
	
in file coderedcms_tags.py:


# Inluded LayoutSettings in this line
from coderedcms.models import Footer, Navbar, LayoutSettings

# and include Site in this line
from wagtail.core.models import Collection, Site


and change get_navbars 

# before

@register.simple_tag
def get_navbars():
    return Navbar.objects.all()


# after

@register.simple_tag
def get_navbars(request):
    curr_url = request.site.hostname
    site = Site.objects.get(hostname=curr_url)
    layout = LayoutSettings.objects.get(site_id=site)
    return Navbar.objects.filter(layoutsetting_id=layout.id)

				
in file navbar.html


# before
	....			
    <div class="collapse navbar-collapse" id="navbar">
      {% get_navbars as navbars %}
      {% for navbar in navbars %}				
	....		
		
# after				
	....			
    <div class="collapse navbar-collapse" id="navbar">
      {% get_navbars request as navbars %}
      {% for navbar in navbars %}				
	....		


# after all i run:
python manage.py makemigrations 
python manage.py migrate

![layout](https://user-images.githubusercontent.com/3496698/60392289-22db7f80-9ad6-11e9-9117-3b51b3adde1a.jpg)
![navbar](https://user-images.githubusercontent.com/3496698/60392290-2cfd7e00-9ad6-11e9-84ed-fbd0ac4d07aa.jpg)


[coderedcms.zip](https://github.com/coderedcorp/coderedcms/files/3342519/coderedcms.zip)

**Comment by rstienstra** [comment]
Getting an error in navbar.html

TemplateSyntaxError at /
'get_navbars' received too many positional arguments

Anyone have an idea?

**Comment by vsalvino** [comment]
Thanks for the legwork @carlosmonari !

I think you may have gone above and beyond what is necessary. The only changed needed would probably be in `get_navbars()`:

before
```python
@register.simple_tag
def get_navbars():
	return Navbar.objects.all()
```
after
```python
@register.simple_tag
def get_navbars(request):
	return Navbar.objects.filter(site=request.site)
```
Since navbars are Snippets they are already associated with a Site by Wagtail. If you get it working, please submit your change as a Pull Request and we can review and merge it in.

**Comment by carlosmonari** [comment]
Hi Vince Salvino,

You considered a ForeignKey site in Object NavBar, but in database doesn´t have this relation.

_return Navbar.objects.filter(site=context['request'].site)_

I previously thought of this, but in my proposal i associate Navbar with LayoutSettings, because the template exists a association with site and other NavBar's properties.

I thought be the better data model to put this property.

When we have change LayoutSetting's in site, we will have a new NavBar too.

look at the attached picture with the actual model and a error when we have implemented just only your suggestion.

	@register.simple_tag(takes_context=True)
	def get_navbars(context):
		return Navbar.objects.filter(site=context['request'].site)


Request Method: | GET
-- | --
http://localhost:8000/
2.2.3
FieldError
Cannot resolve keyword 'site' into field. Choices are: custom_css_class, custom_id, id, menu_items, name


![model_navbar](https://user-images.githubusercontent.com/3496698/60969823-eb02e200-a2f6-11e9-94e8-63483d936364.png)

**Comment by vsalvino** [comment]
@carlosmonari ah yes, my bad, I was thinking of the Settings which are bound to a specific site. The snippets are not. In that case, I think your solution would work. Can you please make a pull request so we can test and review? Thanks!

**Comment by vsalvino** [comment]
Referencing pull request #216

**Comment by wamcvey** [comment]
Looking through the submitted patch, it seems the proposed solution is to have the layout track the navbar to pull in. It'd seem that a similar extension would be needed for the footer—which also is a snippet shared across all sites and pulled in automatically—for this issue to be closed, right?

**Comment by vsalvino** [comment]
For reference, we have carried the original PR and work should now be taking place in branch `merge/pr-216` and PR #251 .

The original solution has the right idea. My thoughts are that we can clean it up a bit and implement it one of these ways:
1. Each navbar and footer has a foreign key to a `Site` or a Home page.
2. The Layout settings can have a m2m (checkboxes) fields to select which navbars and footers for that site.
3. Each page object could have an advanced setting to select (m2m / checkboxes) which navbars and footers to show. If it is blank, it will inherit from the Home page (similar to how the SEO settings work). This adds the advantage of allowing for a sub-page that has a different navbar, with the disadvantage of complicating the page object a bit (i.e. users might think they need to set the navbar on every page they create).

@corysutyak @wamcvey @carlosmonari @FlipperPA  any thoughts on best path forward?

**Comment by wamcvey** [comment]
I like #3 as well. If the navbar selection occurred on the Layout tab of the page object, with some help text similar to SEO, I think end users would understand. I also like that this is a page level control, as it gives a very clean override mechanism to the programmer. I have a site I'm working on now with three classes of end users. Guests (unauthenticated users), Authenticated users to the site, and Members in good standing. The navigable elements of each of these user sets are very different and I believe it'd be easy to implement this dynamic aspect by subclassing the `Page` object and extending the `.select_navbars()` method (or whatever you end up calling it). Having that selection done through either fk relationship status to the site object (#1) or m2m relationship with the site through settings seems much harder to customize.

**Comment by thenewguy** [comment]
Since [snippets lack support for ordering in the wagtail admin](https://docs.wagtail.io/en/stable/topics/snippets.html?highlight=order) something simple like default ordering in the model meta for the name field would suffice for my needs.

It is just important to be able to consistently render one footer below another one.  A prefix like `01 - Footer A`, `02 - Footer B` would make that simple enough
