### ISSUE TITLE
[BUG] Regression Forms fails with non-ascii characters

### ISSUE THREAD

**Issue by lebanonsky** [coderedcorp/coderedcms#213]
**Describe the bug**
Forms filled with non-ascii characters results to error message:

`'ascii' codec can't encode characters in position 510-511: ordinal not in range(128)
`

**Expected behavior**
Works still with previous release 0.14 (Wagtail 2.4/Django 2.1.8)

**Additional context**
I noticed that the submission is actually saved to database but no email will be forwarded because the error.

**Comment by vsalvino** [comment]
Thanks for the bug report @lebanonsky . Did you close this for a reason, did you figure out the issue?

**Comment by lebanonsky** [comment]
I closed it because the system seemed to work in production settings. 
The bug appeared only in dev env when console email backend was active. 
So I figured out that hard to tell if the problem was from coderedcms or wagtail.
