### ISSUE TITLE
[Community] Overiding templates - app sequence is important

### ISSUE THREAD

**Issue by ianastewart** [coderedcorp/coderedcms#217]
I had problems overriding templates until I realised that the sequence in which apps are declared is important. If you are going to override a coderedcms template inside an app, that app must be declared in Settings before the coderedcms app.
While this is all basic Django template handling, it would be worth mentioning in the documentation section on Custom HTML rendering.

**Comment by vsalvino** [comment]
Good suggestion. We could document an example of overriding a template, within the `website` app (which is already configured out of the box to override `coderedcms` app).

Feel free to make a pull request with a doc update :)

**Comment by niccolomineo** [comment]
Django newbie here. What is the structure for e.g. the `navbar.html`? I put the override in `my-project/website/templates/website/snippets/navbar.html` but to no avail.

**Comment by vsalvino** [comment]
You are close, to override a template from coderedcms, put it in a `coderedcms` directory as so:

`my-project/website/templates/coderedcms/snippets/navbar.html`

**Comment by vsalvino** [comment]
@niccolomineo @ianastewart would you both be able to take a look at our new docs, and let me know if that offers a clear explanation? IF not, please suggest improvements!

https://docs.coderedcorp.com/cms/advanced/advanced01.html
