### ISSUE TITLE
css fix for card images incorrectly diplayed in IE 11

### ISSUE THREAD

**Issue by ianastewart** [coderedcorp/coderedcms#225]
When a card that includes a large image is displayed in IE 11, the image gets stretched but renders fine in Chrome, Firefo or, Safari. 
I think it only happens when the image size is greater that the fill size specified in the image tag.
This is strictly an IE bug, but it can be easily fixed by adding the following to a custom css file:
`.card > * {
	flex: 0 0 auto;
}`
Alternatively, to avoid the need for a custom css file so it works out of the box, you could change the image tag to include a style attribute in the various card block templates. Example from `card_block.html`:
`{% if self.image %}
  {% image self.image fill-900x600 as card_img %}
    <img class="card-img-top w-100" style="flex:0 0 auto;" src="{{card_img.url}}" alt="{{card_img.title}}">
    {% endif %}
`

**Comment by vsalvino** [comment]
Good catch. Since we are trying to stick to stock Bootstrap, can you confirm if the IE bug is caused by coderedcms, or bootstrap? For example, does the bug also occur in a simple HTML file with similar card markup loading only bootstrap and no custom CSS?

https://getbootstrap.com/docs/4.3/components/card/

**Comment by ianastewart** [comment]
Vince,
Just tried it with a page that only loads Bootstrap 4.1.3 css from a cdn with the code example you quoted from the Bootstrap docs. I set the card width to 300px and used  placeholder.com to fetch square images of different sizes.
Images are vertically stretched on IE 11 as soon as the image width exceeds the card width, necessitating scaling.
Adding style=”flex: 0 0 auto” fixes it.

I only have IE 11 for testing. I don’t know how it behaves on other versions but Edge is OK. The problem came to light when one of my non-techy customers previewed a site I am generating with coderedcms.
Ian

**Comment by vsalvino** [comment]
Thanks for testing it out Ian. Sounds like this is a bug in Bootstrap then. I would encourage you to file a bug report with Bootstrap here: https://github.com/twbs/bootstrap. I have filed a few bugs with them and they are usually responsive, as long as you provide code samples and demos.
