### ISSUE TITLE
Option to clear cache when updating documents/images/snippets

### ISSUE THREAD

**Issue by vsalvino** [coderedcorp/coderedcms#23]
Currently, the cache is always cleared when publishing a page. However the cache must be manually cleared when changing a document, image, or snippet. When changing a document or image, any cached pages that reference that document will continue to serve the old document URL which results in a 404.

I think it would make sense to have options under the General > Performance settings, to automatically clear the cache when updating:
* Pages
* Documents
* Images
* Snippets

by default all would be turned on. For larger sites that want finer grain control over the cache, they could disable these options and clear the cache manually as needed.

**Comment by corysutyak** [comment]
This issue would belong in https://github.com/coderedcorp/wagtail-cache

**Comment by vsalvino** [comment]
Closing this via #441 , which does not clear on document and image uploads, but does clear on any operation touching a page or snippet. So it should resolve most cache discrepancies.
