### ISSUE TITLE
[BUG] slug generation with accents

### ISSUE THREAD

**Issue by parleweb** [coderedcorp/coderedcms#241]
I assume slugs on internet should not have accents characters for better integration, even if technically its possible.

When I'm create an article title with accents, i got them translated in slug. And makes trouble for editors. In my own models, i use the following to make it works :

```
from django.utils.text import slugify
class MyModel(models.Model):
    #....
    def save(self, *args, **kwargs):
        if not self.slug and self.productName:
            self.slug = slugify(self.productName)
```

**Comment by vsalvino** [comment]
Thanks for the report @parleweb . To the best of my knowledge, unicode characters are valid in a URL. As long as your database supports the relevant charset (we recommend UTF-8), CodeRed/Wagtail/Django should all be able to handle it correctly without error.

Did you experience any breakage or problem in CodeRed CMS with unicode URLs? Or is this more of a user preference?

**Comment by parleweb** [comment]
Hi @vsalvino. 
No break with utf8 in slug for web generation. It's more a user preference.
And I agree with you, it is a wagtail core limitation who force the slugify to allow_unicode to True.
So my very quick developer preference is to patch the ArticlePage classs for example with this code :
`    
class ArticlePage(CoderedArticlePage):
def full_clean(self, *args, **kwargs):
        super().full_clean(*args, **kwargs)
        self.slug = slugify(self.slug)
`
At least, it works fine for my users and no code breaked.

**Comment by vsalvino** [comment]
Great, glad you found a solution. I will close for now as I don't anticipate us changing Wagtail's slug behavior in CodeRed CMS.
