### ISSUE TITLE
Facebook sharing

### ISSUE THREAD

**Issue by milanmaximo** [coderedcorp/coderedcms#252]
Even after update to 0.16 I am not able to share post with image.
Everything is ok when I share on twitter, but on facebook it's appear only link.
I have tested on several meta tags apps, and it shows me that everythings ok, but when I do debging on facebook then I got this 
"The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags. "

Simply Facebook doesn't  see any of images. have you any idea what is going on ?

Site is working perfectly, but I have only issues with sharing.

**Comment by vsalvino** [comment]
Are you overriding or customizing `coderedcms/pages/base.html` template? Most of the logic happens in that template.

**Comment by milanmaximo** [comment]
Yes I did and base.html is the same as it is in coderedcms/pages/base.html I didn't change anything.
Before update I have trying to change meta code inside of block  {# Open Graph SEO #} but nothing happens, it was the same. 
Now is also the same even if this coderedcms/pages/base.html  and mysite/pages/base.html is the same code.

I am stuck with this and I suppose it is something very simple bvut I can't figure out what is it

**Comment by vsalvino** [comment]
Three ideas:
1. Can you try temporarily removing your base.html files, so that it will use the built-in one?
2. Are you using object storage for static/media such as AWS S3, Azure files, etc.?
3. Have you tried debugging using the facebook testing tool? https://developers.facebook.com/tools/debug/ (requires facebook account to use). And sometimes, the tool might cache your page, so try adding a URL parameter to bust the cache, e.g. `/?a=1`

**Comment by milanmaximo** [comment]
> Three ideas:
> 
>     1. Can you try temporarily removing your base.html files, so that it will use the built-in one?
>  When I removed from my website/pages/base.html the image of posts appear when I tested on 
https://ogmeta.ru/en . And it seems good but when I upload back again then I got error and image not showing up.
Also, in same time I've removed from coderedcms/pages/base.html and only base.html was in built-in. So, without those base.html image can be seen and shares on Twitter, so I am so confues why it can\t be shared on Facebook. It's looks so nice when shared a link on Twitter.

>     2. Are you using object storage for static/media such as AWS S3, Azure files, etc.? If so there is an issue for that #240 .
> No, I am using Linode Cloud and I saw this #240, I thought maybe it will help somehow but nothing.

>     3. Have you tried debugging using the facebook testing tool? https://developers.facebook.com/tools/debug/ (requires facebook account to use). And sometimes, the tool might cache your page, so try adding a URL parameter to bust the cache, e.g. `/?a=1`

Yes, I've tried many times, also I've clean cache all this things, but nothing. 
Simply all the time facebook testing tool shows me this 3 errors.

1. Inferred Property
The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags. 

2. Curl Error : SSL_PEER_CERTIFICATE SSL: no alternative certificate subject name matches target host name 'mydomain.com'

3.Errors That Must Be Fixed
Object Missing a Required Value | Object 
at URL  'https://mydomain{.)com'  of type 'website' is invalid because a required property 'og:title' of  type 'string' was not provided.

Really strange, on first tool everythings seems fine, but wehn I use facebook tool it's shoiw me errors and not fetch images.

And Thank you so much for your help

**Comment by vsalvino** [comment]
Oh... I wonder if your domain is not set properly. Can you go to Settings > Site, and edit the site. The host name should be the same as your domain (e.g. `www.example.com`) and the port should be 80 for http:// or 443 for https://

Would you be able to share a link to your page?

**Comment by milanmaximo** [comment]
> Oh... I wonder if your domain is not set properly. Can you go to Settings > Site, and edit the site. The host name should be the same as your domain (e.g. `www.example.com`) and the port should be 80 for http:// or 443 for https://
> 
> Would you be able to share a link to your page?

Well, I already add 443 because the site is under https , but thank you anyway for this.
Yes, you can check here https://kosovskopomoravlje.org/ 

The thing is that this part of sharing issues is important for me, cause I want to migrate one of my projects completely to the  Coderedcms, but still I cant' until not figure out why I can't share posts on FB. :)

**Comment by vsalvino** [comment]
The link you provided (https://kosovskopomoravlje.org/) has an invalid SSL certificate. I would guess that is why FB is not following it.

However your link redirects to https://digitalnasrbija.org/, which appears to have valid opengraph image tags. I can't see anything wrong with it. Although it appears to be a WordPress site 🤔

**Comment by milanmaximo** [comment]
> The link you provided (https://kosovskopomoravlje.org/) has an invalid SSL certificate. I would guess that is why FB is not following it.
> I am using Let's Encrypt for both of sites and I have tested again all the files on server and there is no issues. The first is in WordPress (digitalnasrbija) and second is on CodeRedCms (kosovskopomoravlje) both of them has separate nginx server blocks and as you saw they working. 
My idea was to transfer completely the first site (digitalnasrbija) to CodreRedCms , but as you can see there is a lot of sharing buttons for FB and they are working, and  I just want to leave wordpress completetly but I can't beacuse of this problem with sharing.

> However your link redirects to https://digitalnasrbija.org/, which appears to have valid opengraph image tags. I can't see anything wrong with it. Although it appears to be a WordPress site thinking
Hmm... how did you see that redirects to digitalnasrbija,  cause I have tested already and it's give me 301 and 200 from kosovoskopomoravlje?! really crazy

**Comment by milanmaximo** [comment]
> The link you provided (https://kosovskopomoravlje.org/) has an invalid SSL certificate. I would guess that is why FB is not following it.
> I am using Let's Encrypt for both of sites and I have tested again all the files on server and there is no issues. The first is in WordPress (digitalnasrbija) and second is on CodeRedCms (kosovskopomoravlje) both of them has separate nginx server blocks and as you saw they working.
My idea was to transfer completely the first site (digitalnasrbija) to CodreRedCms , but as you can see there is a lot of sharing buttons for FB and they are working, and I just want to leave wordpress completetly but I can't beacuse of this problem with sharing.

> However your link redirects to https://digitalnasrbija.org/, which appears to have valid opengraph image tags. I can't see anything wrong with it. Although it appears to be a WordPress site thinking

**Comment by milanmaximo** [comment]
> The link you provided (https://kosovskopomoravlje.org/) has an invalid SSL certificate. I would guess that is why FB is not following it.
> 
I am using Let's Encrypt for both of sites and I have tested again all the files on server and there is no issues. The first is in WordPress (digitalnasrbija) and second is on CodeRedCms (kosovskopomoravlje) both of them has separate nginx server blocks and as you saw they working.
My idea was to transfer completely the first site (digitalnasrbija) to CodreRedCms , but as you can see there is a lot of sharing buttons for FB and they are working, and I just want to leave wordpress completetly but I can't beacuse of this problem with sharing.
> However your link redirects to https://digitalnasrbija.org/, which appears to have valid opengraph image tags. I can't see anything wrong with it. Although it appears to be a WordPress site thinking

**Comment by milanmaximo** [comment]
@vsalvino 
It seems that there is some conflict between SSL and domain names.
I have check also with another site which is also hosted on same server, and it's shows same error on Facebook debug.
Thank you so much for support!
