### ISSUE TITLE
form_page layout template

### ISSUE THREAD

**Issue by plascual** [coderedcorp/coderedcms#258]
When I create a form page and then I select LAYOUT > VISUAL DESIGN > Template > Web page without title and cover image, the form isn't displayed on the page anymore.

Is this by design or it could be adapted to let us choose another template than 'default'?

**Comment by vsalvino** [comment]
Yes, what you are describing is the current functionality. I'm not sure how we should handle the default templates - either omit the options from the form page, or update the base template to support having a form element.

**Comment by vsalvino** [comment]
Closing this for now. Keep an eye out for #44 which is related to templating.
