### ISSUE TITLE
Add the function of the external chain to the inner chain like the WordPress golinks plugin

### ISSUE THREAD

**Issue by unihsing** [coderedcorp/coderedcms#259]
Just a suggestion：
Add the function of the external chain to the inner chain like the WordPress golinks plugin.

**Comment by vsalvino** [comment]
Can you please provide more detail, and an example of what this feature is and how it works? I do not know what you mean by external and internal chains.

**Comment by unihsing** [comment]
> Can you please provide more detail, and an example of what this feature is and how it works? I do not know what you mean by external and internal chains.
I am not professional in this regard, so i do not know how it works.
The following example hopes to help you understand.
Requirement: External links are converted to own links, then redirects are implemented.
For example: https://coderedcms.com/go/google/ redirect https://www.google.com/

**Comment by ntbrown** [comment]
> > Can you please provide more detail, and an example of what this feature is and how it works? I do not know what you mean by external and internal chains.
> > I am not professional in this regard, so i do not know how it works.
> > The following example hopes to help you understand.
> > Requirement: External links are converted to own links, then redirects are implemented.
> > For example: https://coderedcms.com/go/google/ redirect https://www.google.com/

This is literally built into Wagtail already: http://docs.wagtail.io/en/v2.0/editor_manual/managing_redirects.html

**Comment by unihsing** [comment]
> > > Can you please provide more detail, and an example of what this feature is and how it works? I do not know what you mean by external and internal chains.
> > > I am not professional in this regard, so i do not know how it works.
> > > The following example hopes to help you understand.
> > > Requirement: External links are converted to own links, then redirects are implemented.
> > > For example: https://coderedcms.com/go/google/ redirect https://www.google.com/
> 
> This is literally built into Wagtail already: http://docs.wagtail.io/en/v2.0/editor_manual/managing_redirects.html

Thank you.By the way, can you set a new tab to open?
I looked at the document and it seems that there is no setting about how the tab is opened.

**Comment by vsalvino** [comment]
As @ntbrown pointed out, redirect functionality is built in to Wagtail. Regarding setting links to open in a new tab, that is a decision Wagtail is against, however we are working on support within coderedcms in issue #254
