### ISSUE TITLE
AMP incorrect tags for Text Block

### ISSUE THREAD

**Issue by pranab-bala** [coderedcorp/coderedcms#263]
#### Describe the bug
article page having text block behaves incorrectly for amp. There are two issues.
1. each text block starts with  tag  html followed by tag body  and ends with  body and html closing tags
2. First image in the block have img-amp tag but subsequent  images have img tag only

this behaviour noticed on .15.2

**Comment by vsalvino** [comment]
Can you please paste a screenshot of your Text Block in the wagtail admin, and also paste a code snippet of how the corresponding HTML is being rendered?

**Comment by pranab-bala** [comment]
thanks vsalvino for responding..
with my limited knowledge,  for the img tag issue .. I believe it has to be with the  utils.py following lines of code:
    try:
        img_tags = soup.find('img')
        img_tags.name = 'amp-img'
    except AttributeError:

we have to loop

following is the snippet of of rendering source .. truncated ..

<html>
--
  | <body>
  | <div class="rich-text">
  | <p>
  | Criteria starts with the column name. Then the contents that needs to be filtered. And Criteria are written side by side. OR conditions are written vertically one after one. Will show some example to explain it
  | </p>
  | </div>
  | </body>
  | </html>
  |  
  |  
  |  
  |  
  |  
  | </div>
  |  
  |  
  |  
  | <div class="col-md
  | ">
  |  
  |  
  |  
  |  
  |  
  |  
  | <html>
  | <body>
  | <div class="rich-text">
  | <h4>
  | Criteria Examples:
  | </h4>
  | <p>
  | If we want to filter only based on Sales figures between $50 and $100, we will use tow Sales column with the following
  | </p>
  | <amp-img alt="AdvCriteria1.png" class="richtext-image right" height="78" src="/media/images/AdvCriteria1.width-500.png" width="248"/>
  | <p>
  | Instead, if we want to see all data for Month Jan, Feb and Mar, we would use the following
  | </p>
  | <p>
  | </p>
  | <img alt="AdvCriteria2.png" class="richtext-image left" height="97" src="/media/images/AdvCriteria2.width-500.png" width="125"/>
  | <p>
  | Next, we want Sales in the Month Jan, Feb and Mar where the sales are between $50 and $100
  | </p>
  | <p>
  | </p>
  | <img alt="AdvCriteria1n2.png" class="richtext-image right" height="93" src="/media/images/AdvCriteria1n2.width-500.png" width="360"/>
  | <p>
  | Please notice that the sales lines are added to each of the month. That is how it works. This also gives flexibility that we can choose different criteria for January and different for the rest of the months
  | </p>
  | <p>
  | Let's further customize it. Let us look for
  | <b>
  | Dry Fruit
  | </b>
  | only for
  | <b>
  | February
  | </b>
  | . For rest of the months, it can be of any Fruit types. So in the the criteria, I do not put anything against
  | <b>
  | Fruit Type
  | </b>
  | in
  | <b>
  | January
  | </b>
  | and
  | <b>
  | March.
  | </b>
  | This will effectively create a logic to show up the rows of January and March, if the Sales value is between $50 and $100, irrespective of fruit types. But for February, the row shows up, only if the sales are between $50 and $100 and the Fruit Type is
  | <b>
  | Dry
  | </b>
  | </p>
  | <p>
  | </p>
  | <img alt="AdvCriteria3.png" class="richtext-image right" height="96" src="/media/images/AdvCriteria3.width-500.png" width="442"/>
  | <p>
  | </p>
  | <p>
  | In the following example, All data for year 2018 + all data for Rob, irrespective of year will show up
  | </p>
  | <p>
  | </p>
  | <img alt="AdvCriteria4.png" class="richtext-image right" height="76" src="/media/images/AdvCriteria4.width-500.png" width="218"/>
  | <p>
  | In the following example, all Sales data of Rob for the year 2018 will show up
  | </p>
  | <p>
  | </p>
  | <img alt="AdvCriteria5.png" class="richtext-image right" height="55" src="/media/images/AdvCriteria5.width-500.png" width="219"/>
  | <p>
  | </p>
  | <h4>
  | Criteria Operators:
  | </h4>
  | <p>
  | Criteria Operators are used for Numeric, currency or date type of data
  | </p>
  | </div>
  | </body>
  | </html>
  |  
  |  
  |  
  |  
  |  
  | <table class="table ">
  |  
  |  
  | <tbody>
  |  
  | <td>Criteria Ooperator</td>
  |  
  | <td>Meaning</td>
  |  
  |  
  |  
  | <tr>
  |  

![Wagtail_-_Editing_Article_How_to_use_advanced_fil_2019-10-10_01-36-04](https://user-images.githubusercontent.com/46047397/66516683-41064200-eaff-11e9-8861-19d246809611.png)

**Comment by pranab-bala** [comment]
I have changed my local utils.py and it is working for the img tag. Added a for loop. 

Still trying to understand where the html and body tags are coming in the text block

def convert_to_amp(value):
    """
    Function that converts non-amp compliant html to valid amp html.
    value must be a string
    """
    soup = BeautifulSoup(value)

    #Replace img tags with amp-img
    try:
        for img_tags in soup.findAll('img'):
                #img_tags = soup.find('img')
                img_tags.name = 'amp-img'
    except AttributeError:
        pass

    return soup.prettify()
