### ISSUE TITLE
How to add a hyperlink to card？

### ISSUE THREAD

**Issue by o5728492** [coderedcorp/coderedcms#266]
How to make a hyperlink to every part of the card can be clicked？
This is much like an image link, but it should be done under the card template to have hyperlinks in all parts.

**Comment by corysutyak** [comment]
You will need to create your own card template and add it to your project settings.  We don't currently have documentation for this feature as it is still experimental and should be used at your own risk.

1. Create a template that is a copy of the card template.
2. Place a copy of `CODERED_FRONTEND_TEMPLATES_BLOCKS` https://github.com/coderedcorp/coderedcms/blob/67871b2bd871d6f76613f297666a468894bd6a4b/coderedcms/settings.py#L127 in your settings file
3. Add an entry to that setting called "cardblock":("/path/to/custom_template.html", "My Custom Template")
5. Run `python manage.py makemigrations website`.  Make sure you only run it on the website app.

Additionally, you could use some custom js to achieve this.

**Comment by vsalvino** [comment]
Alternatively you can simply override the built-in HTML template by making a file in your project:

```
website/templates/coderedcms/blocks/card_foot.html
```

Then edit the contents to render as you wish.

You can see all of our built-in templates here, and copy any of them into your project to change how it renders: https://github.com/coderedcorp/coderedcms/tree/master/coderedcms/templates/coderedcms

**Comment by o5728492** [comment]
Thanks for your help!
