### ISSUE TITLE
Add a Markdown StreamField block option?

### ISSUE THREAD

**Issue by RNCTX** [coderedcorp/coderedcms#269]
#### Is your feature request related to a problem? Please describe.

The default wagtail editor, due to its rich text format, has no practical way of working with in-page anchor links in an editing context (as described in [this issue](https://github.com/wagtail/wagtail/issues/1049) which has been open for four years).  Since the default editor is difficult to extend, no one else has done this either, at least not open source. There is mention of doing so [here](https://www.mashandgravy.co.uk/blog/adding-footnotes-wagtail/) for commissioned custom work.

As that blog post suggests, the most obvious use for this is the ability to write Chicago-style with footnotes and tables of contents.  This is trivial to do in markdown, which has supported complex in-page anchor link generation for quite some time.  

#### Describe the solution you'd like

Since Codered uses a design philosophy of everything optionally being a StreamField block, how about a Markdown StreamField block? The python-markdown library is mature and has included extensions for all of these goodies that wagtail will never likely have in its rich text editor.

https://python-markdown.github.io/extensions/

#### Describe alternatives you've considered

There are documented ways of integrating Markdown with Wagtail, for instance by hijacking the editor with a hook that loads an external Markdown javascript editor on-the-fly.  This isn't optimal, besides being hack'ish, since wagtail's editor/admin/moderator workflows are designed around being multi-user, each user should be able to choose their text formatting preference. Besides, those who choose markdown on purpose don't really need an editor with an integrated preview, since the CMS has this functionality already and the whole point of writing with markdown is to explicitly type your formatting rather than using the editor's menus to do so.

It seems like doing this as a StreamField block that calls a different parser on the output of a plain text field would be a better way.

#### Additional context

N/A

**Comment by vsalvino** [comment]
I agree that a Markdown block would be a nice feature, especially if used where something like a blog page could just have one giant markdown block in lieu of a more complicated streamfield.

However I think we will want to encouraged this to be implemented more as an "addon" than directly built-in to coderedcms. A similar feature request is a code block for doing syntax highlighted source code. We used to have this built in, but it added a lot of overhead to the streamfield and very few installs actually used it, so we split it out. @FlipperPA also maintains wagtail-codeblock which works well with coderedcms.

The caveat here is that we have not yet defined how to properly make a coderedcms "addon" per se. The ideal implementation would automatically hook in; so you could pip install addon, add to installed_apps, and then it would magically appear in your streamfields.

**Comment by RNCTX** [comment]
I'll take a look at the wagtail-codeblock project.

Yeah, I read through your page model code but it's a lot to sort through with no docs in terms of extra data storage and features versus a basic wagtail setup.  

Having to hard-code footnotes is a minor inconvenience versus all of the other functionality you guys have pre-written into this CMS until there's more documentation on extending it.  Thanks!

**Comment by FlipperPA** [comment]
Hey @RNCTX and @vsalvino - I also created this long ago, but deprecated it because of Draftail pretty much support Markdown.

https://github.com/FlipperPA/wagtailmarkdownblock

It used a side-by-side WYSIWYG Markdown editor so you could write in Markdown and get a real-time preview.

**Comment by RNCTX** [comment]
Hmmm, I looked a bit deeper at what Wagtail is using, and...

https://github.com/probablyup/markdown-to-jsx/commit/8764bb181f1f0f8d510cc74d0b417c90698e11b5

That's the library they're using, and that commit says it supports footnotes already? I suppose this probably goes back to their multi-year issue with anchor links in pages that still hasn't been solved.

Wagtail only supports very basic text manipulation with markdown. These more advanced features (which are admittedly out of the spec), no.  The python-markdown lib on the other hand has a lot of officially supported extensions that add all of these features, which is why I was looking to add a python parser to the mix.

I'll take a look at your wagtail plugin, thanks!

**Comment by vsalvino** [comment]
Closing this, as a markdown block should be implemented via a pip package versus built-in.
