### ISSUE TITLE
How to include template contexts in Streamfields?

### ISSUE THREAD

**Issue by chewhoe** [coderedcorp/coderedcms#272]
How to include template contexts in Streamfields?

I want to pass a 'df' variable to template.
When I use wagtail, I do something like this and template contexts are rendered properly.
```
class HomePage(Page):
    body = RichTextField(blank=True)
    content_panels = Page.content_panels + [
        FieldPanel('body', classname="full"),
    ]

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request)
        d = {'df':pd.read_csv('iris.csv.gz').to_dict('split')['data']}
        self.body = Template(self.body).render(Context(d))
        return context
```

When I use coderedcms, the following doesn't work.
```
class WebPageIris(CoderedWebPage):
    class Meta:
        verbose_name = 'Web Page Iris'

    template = 'coderedcms/pages/web_pager.html'

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request)
        d = {'df':pd.read_csv('iris.csv.gz').to_dict('split')['data']}
        context['page'].body = Template(context['page'].body).render(Context(d))
        return context
```

I reckon it's something to do with Streamfields being immutable.

Is there some easy tweak we can do to coderedcms so that template tags will work seamlessly when entered within the admin editor interface? Since the fundamental philosophy is that UI and content is integrated, it makes sense to enable easy access to template variables.

**Comment by vsalvino** [comment]
It looks like you are trying to render the page's body using a context, and then adding the rendered result back into the context? If so I can see that failing. The `body` streamfield is actually a nesting of many other streamfields and is really not designed to be rendered in python.

Could you try this instead:

```python
class WebPageIris(CoderedWebPage):
    class Meta:
        verbose_name = 'Web Page Iris'

    template = 'coderedcms/pages/web_pager.html'

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request)
        d = {'df':pd.read_csv('iris.csv.gz').to_dict('split')['data']}
        context['d'] = d
        return context
```
And then render `d` in your template `coderedcms/pages/web_pager.html`

**Comment by chewhoe** [comment]
Thanks, I can see this working if I want to prepend or append to body. 

Would you know if there's a simple hack that would allow me more flexibility, to insert context variables within the body itself? Maybe the above is not the perfect example, so say instead I'm building a dynamic dashboard. Here I have a standard django view, with a dynamically generated plotly chart which I would typically insert into a template html file as {{ div1 }}. 

```
from pathlib import Path
import plotly.io as pio

def dashboard(request):
    # cols is sorted list of column names of iris.csv
    cols = sorted([col for col in list(pd.read_csv(iris.csv, nrows=0))])

    # div1 is html rendering of plotly chart
    infile = Path('iris.fig1')
    fig1 = pio.read_json(str(infile))
    div1 = py.plot(fig1, output_type='div', include_plotlyjs='cdn')

    context = dict(div1=div1, cols=cols)
    return render(request, 'dashboard.html', context)
```

For a dashboard, prepending or appending wouldn't work, I need the rendering of the context variables within the body itself. How do I enter {{ cols }} and {{ div1 }} inside children blocks of the coderedcms body block, using the wagtail/coderedcms admin interface, and they would be automatically processed by the templating engine?

**Comment by vsalvino** [comment]
The functionality you are describing is more like a snippet. Create a custom snippet that takes a CSV input. Then add a snippet chooser block to your `body` streamfield in `models.py`. Then when your streamfield is getting rendered, it will render the snippet on the page wherever you choose to place your block within the body. This way it is user-changable on each page individually.

However, I would definitely recommend caching the rendered CSV output, as that will make your page loads very slow and eat up a lot of CPU on your server.

**Comment by chewhoe** [comment]
Thanks, will try what was suggested.
