### ISSUE TITLE
How to get the list of pages having common tags?

### ISSUE THREAD

**Issue by meshekhar** [coderedcorp/coderedcms#273]
I want to show list of related blog posts links on the post detail page. The current blog post and the related posts will have common tags. 

Django Taggit has [similar_objects](https://django-taggit.readthedocs.io/en/latest/api.html#TaggableManager.similar_objects) function which returns a list of other objects tagged similarly to the current.

**Comment by vsalvino** [comment]
Hi @meshekhar - checkout [Classifiers](https://docs.coderedcorp.com/cms/stable/features/snippets/classifiers.html) which provides this exact functionality you are describing. We tend to avoid using tags because tags/taggit can also be used for "internal" tagging purposes such as the media library.

**Comment by meshekhar** [comment]
@vsalvino Thanks for the info. As I understand Classifiers would work for CodeRed CMS models. I have many models including django native models therefor i added the following to the BlogPage (CoderedArticlePage model), and it seems to be working as i wanted. Any additional suggestion would be helpful:

```
@property
    def related_posts(self):
        post = get_object_or_404(BlogPage, id=self.id)
        post_tags_ids = post.tags.values_list('id', flat=True)
        posts = BlogPage.objects.filter(tags__in=post_tags_ids).exclude(id=self.id)[:5]
        return posts
```

**Comment by vsalvino** [comment]
Yes, your code snippet would be a good way to accomplish what you need. I would just suggest replacing:
```python
post = get_object_or_404(BlogPage, id=self.id)
```
with
```python
self
```
To save you an extra database query, since `self` is already the current BlogPage.

**Comment by meshekhar** [comment]
Thank you @vsalvino
