### ISSUE TITLE
relation "wagtailcore_site" does not exist

### ISSUE THREAD

**Issue by mronoffon** [coderedcorp/coderedcms#274]
Im getting the following error:

ProgrammingError('relation "wagtailcore_site" does not exist\nLINE 1: ...d_at", "wagtailcore_page"."live_revision_id" FROM "wagtailco...\n                                                             ^\n')
--

Exception:  /usr/local/lib/python3.7/site-packages/django/db/backends/utils.py in _execute, line 84

I can see that the 'wagtailcore_site, wagtailcore_page' tables were created as well
as the field 'live_revision_id'.

This error appears when I attempted to load codered for the first time.  Any ideas on this problem?

Thanks in advance

**Comment by vsalvino** [comment]
Can you please provide steps to reproduce? And also info about your environment (OS, database, python version, etc.)?
