### ISSUE TITLE
DJANGO_SETTINGS_MODULE when deploying through uwsgi

### ISSUE THREAD

**Issue by adminBCI** [coderedcorp/coderedcms#277]
Is the following line necessary in uwsgi.ini when deploying through uwsgi
env = DJANGO_SETTINGS_MODULE=settings.prod

If so, this conflicts with entry in wsgi.prod.py:
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "proj.settings.prod")

Ideally, DJANGO_SETTINGS_MODULE should not be necessary in uwsgi.ini

**Comment by vsalvino** [comment]
Django uses the env variable `DJANGO_SETTINGS_MODULE` to know which settings to use. The line in the wsgi.py file is simply setting that env variable if it is empty as a fallback.

So you can either set the environment variable on your OS/uWSGI, or you can can ignore the environment variable and point uWSGI to a custom `wsgi.py` file and set it yourself.

Consult: https://docs.djangoproject.com/en/2.2/topics/settings/#designating-the-settings
