### ISSUE TITLE
0.17 Release: Master Branch: Spacing in Admin Editor for StreamFields

### ISSUE THREAD

**Issue by FlipperPA** [coderedcorp/coderedcms#280]
#### Describe the bug
The admin still uses significant white space indentation for StreamFields.

#### Steps to reproduce
Create a nested StreamField on a page.

#### Expected behavior
Below, please see how Wagtail 2.7 appears on the edit screen for a **_NON-CODEREDCMS_** page at work with a nested StreamField. This screen shot contains the following StreamBlock indentation (3 levels):

* Section
    * Headline
    * Body
        * [Add New Sub-Block to Section]
        * Paragraph

![image](https://user-images.githubusercontent.com/68164/71534605-eeeae680-28cd-11ea-80af-7ef01ae61bed.png)

Note how little indentation there is for each sub-block. Compare that to CodeRedCMS, where we have the following StreamBlock indentation (5 levels):

* Responsive Grid Row
    * Full Width
    * Content
        * Column
            * Column Size
            * Content
                * [Add New Sub-Block to Content]
                * Text (not visible on screenshot, but...)

![image](https://user-images.githubusercontent.com/68164/71534570-bcd98480-28cd-11ea-908c-cc0131087b69.png)

See how this is still including very significant indentation, push sub-blocks to the right? I've made sure to hard refresh in case this was stale CSS assets, but no luck. It looks like the `Content` field is forcing a significant indentation.

Thanks for your efforts, I won't have time to look at this within the next few days, unfortunately; in the middle of a major site launch!

**Comment by vsalvino** [comment]
Yea, the labels/fields being side-by-side is consistent with how we had the streamfield laid out before. I will try some layout tweaks and see if we can optimize the space a little better.

I think ideally, text boxes and checkboxes could still stay side-by-side to remain compact, but nested streamfields ("content") would stack instead of also being side-by-side

**Comment by FlipperPA** [comment]
Sounds great. I'm hoping to find some cycles to tweak the CSS a bit myself.

That scream you heard from the direction of Philadelphia was my inner voice that is terrified of CSS letting itself out!

**Comment by vsalvino** [comment]
Oh, the wagtail admin CSS is indeed a monster, it certainly was never meant to be toyed with.

I managed to keep the labels and fields horizontal, but nested streamfields are stacked so as to take advantage of the extra width. I think it is much nicer this way.

I have a branch and pull request up, `feature/280-streamfield-tweaks`, please try it out and see if it looks better with your hybrid setup.

**Comment by FlipperPA** [comment]
Much better, thank you sir!

![image](https://user-images.githubusercontent.com/68164/71622494-07941e80-2ba4-11ea-8f23-15dc9d675a73.png)

**Comment by FlipperPA** [comment]
Closing out, thanks @vsalvino :)
