### ISSUE TITLE
Use dynamic image model

### ISSUE THREAD

**Issue by pimarc** [coderedcorp/coderedcms#287]
#### Describe the bug
Wagtail allows to change the image model. I did that because I wanted media images to be stored in a data based directory structure. Everything is ok in Wagtail but not in Codered. In fact some files are linked directly to the standard image model of wagtail (ex logo).

#### Steps to reproduce
1. Create a new codered project
2. Change the wagtail model as described in the wagtail documentation in order to write to another directory. I attach my application models.py as an example of a custom model. The following line must also be added to base.py "WAGTAILIMAGES_IMAGE_MODEL = 'website.CustomImage'" and then makemigrations and migrate.
3. Do migrations and go to admin
4. Try to set a logo in the layout
5. This produces an error

#### Expected behavior
I corrected the problem myself but I expect it to be corrected in a future release. The correction is quiet simple:
1. add "from wagtail.images import get_image_model_string" to the wagtailsettings_models.py, page_models.py and snippet_models.py files.
2. replace all occurences of 'wagtailimages.Image' with get_image_model_string()
3. do migrations
[models.py.txt](https://github.com/coderedcorp/coderedcms/files/4083618/models.py.txt)

Eveything is working again then

**Comment by vsalvino** [comment]
Thank you for this info! Could you submit a pull request with the fix? Would me much appreciated.

**Comment by pimarc** [comment]
Done

Regards

Pierre

**Comment by vsalvino** [comment]
Closed by PRs #288 and #336
