### ISSUE TITLE
How to override AnalyticsSettings model?

### ISSUE THREAD

**Issue by moskrc** [coderedcorp/coderedcms#292]
Hi,

I wanna add few fields into Settings->Tracking form. A checkbox and char field for configure Google Tag Manager. 

<img width="940" alt="Screen Shot 2020-01-24 at 16 12 18" src="https://user-images.githubusercontent.com/364857/73071993-2f398680-3ec5-11ea-957b-502238d8bf13.png">

Like this:

<img width="1300" alt="Screen Shot 2020-01-24 at 16 12 28" src="https://user-images.githubusercontent.com/364857/73072006-35c7fe00-3ec5-11ea-9920-fa58665e3e43.png">

If I write this:

```
@register_setting(icon='fa-google')
class CustomAnalyticsSettings(wagtailsettings_models.AnalyticsSettings):
    """
    Tracking and Google Analytics.
    """
    class Meta:
        verbose_name = _('Tracking')
        
    gtm_container_id = models.CharField(
        blank=True,
        max_length=255,
        verbose_name=_('GTM Container ID'),
        help_text=_('Your Google Tag Manager container ID (begins with "GTM-")'),
    )
    
    gtm_is_enabled = models.BooleanField(
        verbose_name=_('GTM is enabled'),
        default=False
    )
        
    ga_tracking_id = models.CharField(
        blank=True,
        max_length=255,
        verbose_name=_('GA Tracking ID'),
        help_text=_('Your Google Analytics tracking ID (begins with "UA-")'),
    )
    ga_track_button_clicks = models.BooleanField(
        default=False,
        verbose_name=_('Track button clicks'),
        help_text=_('Track all button clicks using Google Analytics event tracking. Event tracking details can be specified in each button’s advanced settings options.'),  # noqa
    )

    panels = [
        MultiFieldPanel(
            [
                FieldPanel('gtm_container_id'),
                FieldPanel('gtm_is_enabled'),
            ],
            heading=_('Google Tag Manager')
        ),        
        MultiFieldPanel(
            [
                FieldPanel('ga_tracking_id'),
                FieldPanel('ga_track_button_clicks'),
            ],
            heading=_('Google Analytics')
        )
    ]

```

I see errror: 

```
django.core.exceptions.FieldError: Local field 'ga_tracking_id' in class 'CustomAnalyticsSettings' clashes with field of the same name from base class 'AnalyticsSettings'.
```

How to do it in the correct way? 

And how to hide the section? How to remove it from the admin panel?

Thanks!

**Comment by vsalvino** [comment]
Because our `AnalyticsSettings` is a concrete model (meaning it exists in the database), Django internally actually creates two objects (an `AnalyticsSettings` and a `CustomAnalyticsSettings`) and makes a "foreign key" of sorts between them. That is why in Django you cannot override a field of a parent model if the parent model is Concrete (you can only override Abstract model fields).

In your case, you can just delete that field from your `CustomAnalyticsSettings` model, because it already exists on the parent model. Then call `CustomAnalyticsSettings.ga_tracking_id` and it should work.

While this doesn't exactly answer your question, I would actually like to support GTM in our analytics model. If you have support for GTM working in your project, I would be happy to merge that into coderedcms if you're willing to make a pull request.

**Comment by moskrc** [comment]
@vsalvino Thanks you! 

My code is:

```python
from coderedcms.models import AnalyticsSettings
from django.db import models
from django.utils.translation import ugettext_lazy as _
from wagtail.admin.edit_handlers import FieldPanel, MultiFieldPanel
from wagtail.contrib.settings.models import register_setting


@register_setting(icon='fa-google')
class CustomAnalyticsSettings(AnalyticsSettings):
    """
    Tracking and Google Analytics.
    """
    class Meta:
        verbose_name = _('Tracking')
        
    gtm_container_id = models.CharField(
        blank=True,
        max_length=255,
        verbose_name=_('GTM Container ID'),
        help_text=_('Your Google Tag Manager container ID (begins with "GTM-")'),
    )
    
    gtm_is_enabled = models.BooleanField(
        verbose_name=_('GTM is enabled'),
        default=False
    )
        
    panels = [
        MultiFieldPanel(
            [
                FieldPanel('gtm_container_id'),
                FieldPanel('gtm_is_enabled'),
            ],
            heading=_('Google Tag Manager')
        ),        
        MultiFieldPanel(
            [
                FieldPanel('ga_tracking_id'),
                FieldPanel('ga_track_button_clicks'),
            ],
            heading=_('Google Analytics')
        )
    ]
```

Now I have:

<img width="1011" alt="Screen Shot 2020-01-28 at 11 06 36" src="https://user-images.githubusercontent.com/364857/73245848-45de2700-41be-11ea-9773-c36bf6733df2.png">

Perhaps, overriding the model is not the best way. Just looking for how to add a new field to Settings->Tracking form.

**Comment by vsalvino** [comment]
The simplest way would be to create your own settings model: https://docs.wagtail.io/en/v2.7.1/reference/contrib/settings.html

However, I would like to support GTM - so if you are able to create a pull request with GTM support for our analytics settings, I would be happy to review and merge that in.
