### ISSUE TITLE
Customizing Webp images output format

### ISSUE THREAD

**Issue by plascual** [coderedcorp/coderedcms#295]
I noticed that uploading Webp images in CodeRedCMS results in PNG conversion.

I've read on Wagtail documentation that it is possible to specify output formats by changing WAGTAILIMAGES_FORMAT_CONVERSIONS setting in wagtail/images/models.py. 

For example:

WAGTAILIMAGES_FORMAT_CONVERSIONS = {
    'bmp': 'jpeg',
    'webp': 'webp',
}

https://docs.wagtail.io/en/v2.7.1/advanced_topics/images/image_file_formats.html#image-file-formats

How would it be possible to make this override in CodeRedCMS?

Thanks in advance!

**Comment by vsalvino** [comment]
Good question. It should be possible to override that setting, we do not tamper with wagtail images at all. I think the only image we intentionally convert to PNG is the favicon, which might be causing your problem.

Could you provide some screenshots or live examples of your problem with webp?

**Comment by plascual** [comment]
When I upload a Webp image, the original is left untouched in "original_images" folder, and Wagtail converts Webp images as PNG by default and stores it in "images" folder". This behavior is described in Wagtail docs: "By default all bmp and webp images are converted to the png format when no image output format is given."

Using the setting WAGTAILIMAGES_FORMAT_CONVERSIONS would prevent conversion to PNG. I'm not sure how to override Wagtail.

**Comment by vsalvino** [comment]
Ah. That setting would go in your Django settings file. If you're using a normal coderedcms setup, you could put it in your `{projectname}/settings/base.py` file. Let me know if that works.

**Comment by plascual** [comment]
Yes, that works! Thanks for the prompt answer!
