### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by corysutyak** [coderedcorp/coderedcms#3]
Add documentation. Critical pieces that are required for 1.0 milestone:

- Quickstart
    - [x] Install
    - [ ] Deploying
- Basic Tutorial
    - [x] Setup, branding, getting started
    - [x] Adding home page content
    - [x] Adding a blog
    - [x] Categorize the blog
    - [x] Adding a basic contact form
    - [x] Customizing navbar and footer
    - [x] Coding: add a custom field to WebPage model and template
- Features
    - [x] Page types
    - [x] Block types
    - [x] Snippets
    - [ ] Settings (wagtail)
- Customizing
    - [x] Custom CSS/JS
    - [x] Overriding templates
- How-To
    - [x] SEO
    - [ ] Using a different frontend CSS framework
    - [ ] AMP Pages
    - [x] Making custom page types
    - [ ] Making custom blocks
- [x] Settings (django)
- [x] Contributing guide
- [ ] Roadmap

**Comment by unihsing** [comment]
Can multi-language example tutorials be supported?
