### ISSUE TITLE
Why can't I just add Content with the RichTextEditor?

### ISSUE THREAD

**Issue by guettli** [coderedcorp/coderedcms#301]
I am editing a page.

I see these types to add:

![no-richtext--strange](https://user-images.githubusercontent.com/414336/75923249-f9dd6c80-5e64-11ea-876a-4af3d2bc6364.png)

Why can't I just add content (HTML) with the RichTextEditor?

**Comment by corysutyak** [comment]
A core concept of this CMS is that you are able to create layout with content.  By doing so, content editors are empowered to more easily control the look and feel of their web pages.  Content editors are able to create their own grid layouts as they see fit, on a per page basis.  To achieve what you're asking for, you would click the "Responsive Grid Row" field, then setup a 1 column row.  In that row would be a traditional wagtail RichTextEditor block.

We understand this goes against traditional wagtail.  If you want a page that's more traditional, you are more than able to create a new Page model that allows the functionality you're looking for.  At the end of the day, everything that's in this CMS is just an extension of Wagtail.

**Comment by guettli** [comment]
Thank you for your fast and detailed reply. 

I guess I won't use CodeRed. First I was amazed, but somehow it is too much.

In my current usecase i need a very simple solution, which has only very few features and options.

Again, thank you for your support.
