### ISSUE TITLE
Lost after Tutorial: How to show the navbar?

### ISSUE THREAD

**Issue by guettli** [coderedcorp/coderedcms#302]
I did the tutorial. Now I am lost: How to show the navbar?

It would be nice, if you could fill the "todo" here: 

https://docs.coderedcorp.com/cms/stable/getting_started/tutorial03.html

**Comment by mwort** [comment]
Just create a menu in Snippets > Navigation bar. By default they get all displayed in the main navabar, which I also find a bit counter-intuitive. I think it would be good to be able to select the menu for the navbar under Settings > Layout > Site navbar layout.

**Comment by vsalvino** [comment]
@guettli  - yes unfortunately there is still a lot of tutorials and documentation that needs to be written 😵

@mwort there is an issue related to what you're describing - see #251

**Comment by vsalvino** [comment]
New tutorial, and advanced tutorial, have been published!

https://docs.coderedcorp.com/cms/getting_started/tutorial01.html

**Comment by guettli** [comment]
thank you.
