### ISSUE TITLE
Default value of "Show child pages"? (NavBar)

### ISSUE THREAD

**Issue by guettli** [coderedcorp/coderedcms#303]
#### Is your feature request related to a problem? 

This is not a problem, but I think it would make sense for new users to change the default
value of "Show child pages" to "true". Up to now it is "false".

![image](https://user-images.githubusercontent.com/414336/75925447-0237a680-5e69-11ea-863c-00617ce2e2ce.png)

I think/guess most people want this child pages to be visible.

But maybe I am wrong.

**Comment by vsalvino** [comment]
This is difficult to say as it is a matter of opinion. In most of our website buildouts we lean towards simpler navigation versus too many nested menus. So for us it makes sense to be off by default.

I would not be inclined to change this right now unless many others also request this change and provide arguments for it.

**Comment by guettli** [comment]
Thank you for your reply. Let's see what new comers want in the future.
