### ISSUE TITLE
Embedded media Youtube URL with "enablejsapi=1" parameter

### ISSUE THREAD

**Issue by plascual** [coderedcorp/coderedcms#304]
Hi!

We use a Youtube video tracker that needs the "enablejsapi=1" parameter to be in the URL instead of iframe attribute element. When I paste the a URL with this parameter in CodeRedCMS, it is automatically stripped.

Where should I dig to accomodate this particular need, and keep this parameterin the URL?

Thanks in advance!

**Comment by vsalvino** [comment]
Good question. This is handled by wagtail's embed block, which we wrap with just a light amount of HTML code.

Our Embed block: https://github.com/coderedcorp/coderedcms/blob/e08c628e63ff56a462e056dc39c75542680a295b/coderedcms/blocks/html_blocks.py#L99-L112

Wagtail embeds documentation: https://docs.wagtail.io/en/stable/advanced_topics/embeds.html

I would recommend asking on the wagtail slack for more help. https://wagtail.io/slack/

**Comment by plascual** [comment]
Thanks!

As it is also considered a good practice to put the "enablejsapi" parameter as an iframe attribute element, I might check on the tracker side compatibility instead.

For reference: (https://developers.google.com/youtube/iframe_api_reference#Examples)

**Comment by vsalvino** [comment]
If you get stuck you can just use an `HTML Block` and put the raw embed code in yourself.
