### ISSUE TITLE
Multilingual Coderedcms

### ISSUE THREAD

**Issue by milanmaximo** [coderedcorp/coderedcms#310]
Is it there any option how to create multilingual Coderedcms... Two or three more languages on site ?
Or if anyone have an idea how to do it...
Thanks a lot

**Comment by vsalvino** [comment]
We do have a little bit of documentation on that, which might help: https://docs.coderedcorp.com/cms/stable/how_to/translation.html

There is also an issue for internationalization, which may or may not be relevant (it is a bit old): https://github.com/coderedcorp/coderedcms/issues/57

Generally speaking, any method that can help add translations in Wagtail should work similarly in coderedcms.

**Comment by vsalvino** [comment]
Please add further discussion on #57

**Comment by milanmaximo** [comment]
> We do have a little bit of documentation on that, which might help: https://docs.coderedcorp.com/cms/stable/how_to/translation.html
> 
> There is also an issue for internationalization, which may or may not be relevant (it is a bit old): #57
> 
> Generally speaking, any method that can help add translations in Wagtail should work similarly in coderedcms.

Thank you so much for answer. I will try it.
