### ISSUE TITLE
In Admin, JS and CSS do not load on fresh install (version 0.18)

### ISSUE THREAD

**Issue by e-mojo** [coderedcorp/coderedcms#311]
#### Describe the bug
I've setup RedCMS on Django & Wagtail and installed everything. Haven't compiled using SASS. Front end looks good, but for the backend, the CSS and JS isn't loading, preventing me to do anything else.

These sources don't load:

`<link rel="stylesheet" href="/static/wagtailadmin/css/normalize.css?v=3c0ce529" >`
`<link rel="stylesheet" href="/static/wagtailadmin/css/vendor/jquery-ui/jquery-ui-1.10.3.verdant.css?v=3c0ce529" >`
`<link rel="stylesheet" href="/static/wagtailadmin/css/vendor/jquery.tagit.css?v=3c0ce529">`
`<link rel="stylesheet" href="/static/wagtailadmin/css/core.css?v=3c0ce529" type="text/css" />`
`<link rel="stylesheet" type="text/css" href="/static/coderedcms/css/codered-admin.css">`
`<link rel="stylesheet" href="/static/wagtailfontawesome/css/wagtailfontawesome.css">`
`<link rel="stylesheet" href="/static/wagtailadmin/css/layouts/home.css?v=3c0ce529" type="text/css" />`
```
<script src="/static/wagtailadmin/js/vendor/modernizr-2.6.2.min.js?v=3c0ce529"></script>
<script src="/static/wagtailadmin/js/vendor/jquery-3.2.1.min.js?v=3c0ce529"></script>
<script src="/static/wagtailadmin/js/vendor/jquery-ui-1.12.1.min.js?v=3c0ce529"></script>
<script src="/static/wagtailadmin/js/vendor/jquery.datetimepicker.js?v=3c0ce529"></script>
<script src="/static/wagtailadmin/js/vendor/jquery.autosize.js?v=3c0ce529"></script>
<script src="/static/wagtailadmin/js/vendor/bootstrap-transition.js?v=3c0ce529"></script>
<script src="/static/wagtailadmin/js/vendor/bootstrap-modal.js?v=3c0ce529"></script>
<script src="/static/wagtailadmin/js/vendor/bootstrap-tab.js?v=3c0ce529"></script>
<script src="/static/wagtailadmin/js/vendor/tag-it.js?v=3c0ce529"></script>
<script src="/static/wagtailadmin/js/core.js?v=3c0ce529"></script>
<script src="/static/wagtailadmin/js/vendor.js?v=3c0ce529"></script>
<script src="/static/wagtailadmin/js/wagtailadmin.js?v=3c0ce529"></script> 
```
`

#### Steps to reproduce
Making a clean install should lead to the same issues. 

#### Expected behavior
I actually don't see the folder wagtailadmin anywhere in the current release, so not sure if this is related to the package or if it is related to my install/setup. I've looked in previous versions and there too the structure is different and these files and folders are missing.

#### Additional context
Using Python 3.8, Django 3.0.5 and Wagtail 2.8.

**Comment by vsalvino** [comment]
I'm betting this is due to your static file configuration.

1 - Under a normal coderedcms install, it is configured to serve static files when `DEBUG=True`. As long as this code was not removed in your `urls.py`:
https://github.com/coderedcorp/coderedcms/blob/c2373f8f1431b068fffe0d5978aa6846407251a3/coderedcms/project_template/basic/project_name/urls.py#L31-L37

2 - Assuming that code is there and works in development, when you go to deploy to production or to a "real" web server, you will need to configure your server to serve those files - Django will not serve them, giving you the 404. More info is available here: https://docs.djangoproject.com/en/3.0/howto/static-files/deployment/

(I realize static and media files are a huge pain point of working with Django - if you are looking for a simple hosting solution consider signing up for our beta https://www.codered.cloud/)

**Comment by e-mojo** [comment]
Thank you for your fast reply. I don’t think it is related to serving the static files or some Nginx setting. I actually don’t see the files referenced. There is no folder with these files anywhere, couldn’t find them by searching using the file names. This isn’t my first Django nor Wagtail project, and I do know how to setup static directories. Any thoughts are most welcome!

Met vriendelijke groet / With kind regards,

Erwin Moojen
22 Times
+31617476202
________________________________

**Comment by vsalvino** [comment]
Those files are not part of our project. They are static files from Wagtail: https://github.com/wagtail/wagtail/tree/stable/2.8.x/wagtail/admin/static_src/wagtailadmin

In my experience, if one static file does not load, then none of them probably load. For example, does your site also experience a 404 on the front-end (home page) loading `/static/coderedcms/js/codered-front.js`? Or in the Django admin? (`/django-admin/` URL would be missing various usual styles)?

If the coderedcms static files load, but the wagtailadmin files do not load, then that would probably be related to something missing in `INSTALLED_APPS` or `STATICFILES_FINDERS` in `project_name/settings/base.py`. See an example of the required values here: https://github.com/coderedcorp/coderedcms/blob/master/coderedcms/project_template/basic/project_name/settings/base.py

**Comment by vsalvino** [comment]
Closing since this seems to be a static file serving issue.
