### ISSUE TITLE
Docker feature

### ISSUE THREAD

**Issue by Allan-Nava** [coderedcorp/coderedcms#314]
Is possible to implement with docker?

**Comment by safaci2000** [comment]
I'm using a variation of cookie cutter with wagtail/codered I can share if you'd like but it would be nice if out of the box it would have a standard docker setup.  

That being said, that also implies some opinionated choices.  

https://cookiecutter-django.readthedocs.io/en/latest/

**Comment by ayushin** [comment]
This `Dockerfile` works well with the kubernettes but will work in any docker environment:
```
FROM python:3.6
LABEL maintainer="aahi"

RUN apt-get update -y && apt-get install -y libmagickwand-dev libmagickcore-6.q16hdri-6-extra

ENV PYTHONUNBUFFERED 1
#ENV DJANGO_ENV dev

COPY /requirements /code/requirements
RUN pip install -r /code/requirements/production.txt

COPY . /code/
WORKDIR /code/

EXPOSE 8080
CMD exec gunicorn aahi.wsgi:application --bind 0.0.0.0:8080 --workers 3
```

and cloudbuild.yaml to go with it if you wanted:

```
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/codered', '-f', 'Dockerfile', '.' ]
images:
- 'gcr.io/$PROJECT_ID/codered'
```

**Comment by Allan-Nava** [comment]
> This `Dockerfile` works well with the kubernettes but will work in any docker environment:
> 
> ```
> FROM python:3.6
> LABEL maintainer="aahi"
> 
> RUN apt-get update -y && apt-get install -y libmagickwand-dev libmagickcore-6.q16hdri-6-extra
> 
> ENV PYTHONUNBUFFERED 1
> #ENV DJANGO_ENV dev
> 
> COPY /requirements /code/requirements
> RUN pip install -r /code/requirements/production.txt
> 
> COPY . /code/
> WORKDIR /code/
> 
> EXPOSE 8080
> CMD exec gunicorn aahi.wsgi:application --bind 0.0.0.0:8080 --workers 3
> ```
> 
> and cloudbuild.yaml to go with it if you wanted:
> 
> ```
> steps:
> - name: 'gcr.io/cloud-builders/docker'
>   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/codered', '-f', 'Dockerfile', '.' ]
> images:
> - 'gcr.io/$PROJECT_ID/codered'
> ```

Thank u!

**Comment by vsalvino** [comment]
We currently provide Wagtail's docker file in new coderedcms projects by default. I think it should suffice for now, although anyone on this thread is certainly welcome to make a PR for documentation on running coderedcms with docker :)
