### ISSUE TITLE
Problem when migrating website db

### ISSUE THREAD

**Issue by lebanonsky** [coderedcorp/coderedcms#315]
Trying to migrate from sqlite3 to mysql but got hung up with settings table:

` Could not load contenttypes.ContentType(pk=11): (1062, "Duplicate entry 'coderedcms-adasettings' for key 'django_content_type_app_label_model_76bd3d3b_uniq'")`

what would be the correct way to fix this?

**Comment by vsalvino** [comment]
I don't believe converting from one database backend to another is supported by Django, not without a lot of problems. I have only done this once before and it was extremely fraught with problems.

How are you doing the migration?

**Comment by lebanonsky** [comment]
I was following this guide: https://www.shubhamdipt.com/blog/django-transfer-data-from-sqlite-to-another-database/

python manage.py dumpdata > db.json
Change the database settings to new database such as of MySQL / PostgreSQL.
python manage.py migrate
python manage.py shell 
Enter the following in the shell
from django.contrib.contenttypes.models import ContentType
ContentType.objects.all().delete()
python manage.py loaddata db.json

But I could not remove content types bacause foreign key constraints. I assume content types are created in initial migration and cannot be imported in the dump.
