### ISSUE TITLE
SectionBlock?

### ISSUE THREAD

**Issue by ayushin** [coderedcorp/coderedcms#316]
Hi,

Just figuring out how to structure content of a single page website.

So far it seems to be that adding a SectionBlock layout streamblock that you can use in ReusableContent snippet might be the way to go?

Is that something you'd like to include in the core code or do I miss something obvious?

**Comment by vsalvino** [comment]
The Bootstrap way to create sections would be: Container > Row > Columns. So we tend to follow that paradigm in coderedcms.

Creating a Responsive Grid Row block renders a container and row divs in the HTML. You can add custom CSS classes and toggle full width container size:
```html
<div class="container[-fluid] [custom_css_class]">
  <div class="row">
    ....
  </div>
</div>
```
Within the row you can add any number of columns, including full-width columns.

We also have a Hero Unit Block, which provides an additional outer div with optional background image and color controls. Within the Hero Unit Block you can create a Responsive Grid Row, or enter raw HTML, so you have total control.

If you wanted some other structure, then I would recommend making your own block class and adding it into the `body` field of your page class.

**Comment by ayushin** [comment]
Thanks for the response, not what I was talking about, but super helpful!

In what I need is a Duplicate of #305
