### ISSUE TITLE
Page link to a fragment ID

### ISSUE THREAD

**Issue by ayushin** [coderedcorp/coderedcms#318]
Trying to find if this is supported and if so how to do it.

I'd like to be able to have a page link (and hence do not open in a new window) to lets say home#contact

How?

**Comment by vsalvino** [comment]
This is technically not supported. Our workaround has been to use the "external link" field and put the page URL manually, i.e.: `/page/#fragment`

I had an idea, that if the `page` attribute of the link block was filled out, and the `external` field was also filled out, the external field would be appended after the page link. Do you think this would be an elegant or acceptable solution?

**Comment by vsalvino** [comment]
New feature: Link to a fragment ID on a page (e.g. `/page/#fragment`).

Requirements:
* Use the existing ButtonLink block
* Select the page in the ButtonLink block
* In the external URL input, add the fragment (e.g. `#fragment`)
* The output HTML should dynamically render the page slug, and append the fragment.
