### ISSUE TITLE
pipenv install coderedcms error with beautifullsoup version

### ISSUE THREAD

**Issue by parleweb** [coderedcorp/coderedcms#324]
It seems the new version requirement made by django-bootstrap4 package for beautifullsoup broke the compatibility with coderedcms and wagtail as it using now version 4.9.1 and wagtail stop at 4.8.
It works with pip but not with pipenv.
Using django-bootstrap4 version 1.1.0 is fine.

Pipfile working :

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
django-bootstrap4 = "==1.1.0"
coderedcms = "*"

[requires]
python_version = "3.8"
```

Without, it broke.

**Comment by eeintech** [comment]
I've used the required version for Wagtail and it still works. You can install CodeRedCMS before Wagtail and you should be good to go!

**Comment by vsalvino** [comment]
We will investigate the dependency chain. I believe currently that version should be pinned same as wagtail's requirement.

**Comment by vsalvino** [comment]
Merged to master
