### ISSUE TITLE
Hosting the blog

### ISSUE THREAD

**Issue by vCloudernBeer** [coderedcorp/coderedcms#328]
After I built the blog on my local computer, how can I host my blog so other people can access it?  Or can someone please point me to the documentation regarding this issue?

**Comment by vsalvino** [comment]
We are missing a hosting guide on our docs, this is on the backlog. However, you can host CodeRed CMS the same as any other Django project (I realize that is probably not helpful though!).

To start, I'd recommend looking at the Wagtail deployment guide: https://docs.wagtail.io/en/v2.9/advanced_topics/deploying.html

We have also started offering a CodeRed hosting service, in beta, which is free to sign up for if you want to give it a try.
Register:  https://app.codered.cloud/register/
Quickstart: https://www.codered.cloud/docs/coderedcms/quickstart/

Hope this helps for now until we have more robust documentation.

**Comment by jly02087** [comment]
I was having trouble with this as well, I am new to this, but I just kept trying and reading until I got a solution using pythonanywhere.com. Here is a walkthrough I put together for myself: [CodeRed CMS deployment to pythonanywhere.com](https://www.theinsidetrade.com/blog/how-to-setup-a-website-for-free/)

**Comment by vsalvino** [comment]
We have since launched CodeRed cloud, optimized for Wagtail hosting, and have also updated the Wagtail deployment docs on wagtail.org.

However I agree that we should add a note about hosting/deploying on our docs.
