### ISSUE TITLE
Wagtail 2.11 upgrade

### ISSUE THREAD

**Issue by vsalvino** [coderedcorp/coderedcms#335]
So far this is one known issue with CodeRed CMS on Wagtail 2.10: https://github.com/wagtail/rfcs/issues/57

This can probably go out in the next release, 0.20, if it is ready in time.

**Comment by eeintech** [comment]
I'm clearly not an expert in Wagtail but the import of the [SubmissionsListView](https://docs.wagtail.io/en/latest/reference/contrib/forms/customisation.html#customise-form-submissions-listing-in-wagtail-admin) method is what's causing the `django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.` error.
I've created a clean Wagtail project and tested this in `2.9.3` and `2.10rc` and only got the error with the latter, as reported in the wagtail/rfcs#57. 
The current Wagtail doc does not offer a workaround, so until then CodeRedCMS should stick with `2.9.x`.

**Comment by eeintech** [comment]
@vsalvino The `rc2` seemed to have solved that issue, however, I found another one which seems to be exclusively related to CodeRedCMS (no issue with a pure Wagtail project): secondary menu panel icons seem to be shifted to the left, see screenshot below

![image](https://user-images.githubusercontent.com/4020546/89075333-92f4ae80-d343-11ea-86f4-07a54e577c07.png)

**Comment by vsalvino** [comment]
Thank you Matt!

Yes this is a coderedcms problem... we do have to tamper with the wagtail admin CSS with each release. As mentioned by Matt during Wagtail Space today, there is a lot of "internal APIs" within the wagtail admin. We should probably put some of our CSS changes into upstream Wagtail. Regardless this is definitely a `codered-admin.css` thing which commonly needs tweaked with each wagtail release.
