### ISSUE TITLE
Show CodeRed CMS Version 

### ISSUE THREAD

**Issue by WMeldon** [coderedcorp/coderedcms#34]
Should probably start maintaining a version in the CMS that is visible on the admin panel and command line.  Most python projects appear to do this with a ```__version__``` variable in ```setup.py```

**Comment by vsalvino** [comment]
Yes, I was thinking this exact same thing. Wagtail shows their version in the title attribute of the logo and under the settings panel in the admin. I propose that we replace this with our version; our version is pinned to a specific wagtail version it doesn't really need to show both. Thoughts?

**Comment by WMeldon** [comment]
Sounds good to me.
