### ISSUE TITLE
Exclude paths from sitemap.xml

### ISSUE THREAD

**Issue by plascual** [coderedcorp/coderedcms#355]
Hello! Is there any way to exclude specific paths from the XML sitemap ?

Thanks

**Comment by vsalvino** [comment]
The sitemap feature uses Wagtail's sitemap generator. You can see how to customize it here: https://docs.wagtail.io/en/stable/reference/contrib/sitemaps.html#customising

In short, you need to add a function to your page models (in `website/models.py`), which will customize all of the sitemap entries generated based on that page type.

```python
class MyPage(Page):

    def get_sitemap_urls(request):
        # Return an empty list to exclude all pages of MyPage type from the sitemap.
        return []
```

**Comment by plascual** [comment]
Thanks to point it out!

If it can be useful for anyone, here is the code I used to remove specific path from the sitemap:

```
def get_sitemap_urls(self, request):
    if self.slug == 'foo':
        return []
    else:
        return super().get_sitemap_urls(request)
```
