### ISSUE TITLE
Testable Page

### ISSUE THREAD

**Issue by thenewguy** [coderedcorp/coderedcms#365]
I was just thinking about how a testable page would work.  Is this something you've considered adding to the Page types?  Seems like it would fit with the goal of the CodeRed project.

Something like TestableParentPage that redirects with a temporary redirect to one of its immediate TestableChildPage children.  The  TestableParentPage could have any type of child page but the TestableChildPage would only be allowed under an instance of TestableParentPage.

If there is only one active TestableChildPage perhaps the TestableParentPage just renders the child - but maybe just use the same redirection for simplicity.  There could be a weighting algorithm, but perhaps just simplest use would be a random choice per session.  The redirection would make it easy to make use of caching - say, only changing the redirect once every minute or something instead of using sessions for a per user choice.

**Comment by vsalvino** [comment]
When you say testable page... are you referring to unit tests? Or more like A/B testing?

**Comment by thenewguy** [comment]
More like A/B testing

**Comment by vsalvino** [comment]
Have you looked into https://github.com/torchbox/wagtail-experiments ? I have never used it, but it seems to be the most "official" a/b testing method for Wagtail. Assuming that does the job, I would think the best approach would be to support an integration or a how-to guide for using wagtail-experiments with coderedcms.

**Comment by thenewguy** [comment]
I will have to take a closer look.  Initial glance looks like that tracks the goals in the back end. I was thinking a little lighter for hooking in with browser side analytics and still being able to make use of cdn style page caching instead of a persistent session rendering approach.

**Comment by thenewguy** [comment]
Going to close the issue - it doesn't need to be part of CodeRed if you don't want it to be.  Just curious if it was an interesting topic since it goes along with marketing sites

**Comment by vsalvino** [comment]
I would consider the feature, just didn't want to "reinvent the wheel" if the wagtail-experiments already worked as necessary.

The feature would probably need to be a special model (e.g. `ABTest`), which could select two (or multiple) pages, and set various criteria on how they would be served (randomly, round robin, by user-agent, etc.).

We are trying to slowly split features of coderedcms into more generic wagtail-friendly pip packages, so they can be reused in the rest of the wagtail world... so if you are interested in implementing a feature, it would be best to keep it somewhat wagtail generic and then we could incorporate that into coderedcms.
