### ISSUE TITLE
Mailchimp integration

### ISSUE THREAD

**Issue by vsalvino** [coderedcorp/coderedcms#37]
We need the ability to integrate form submissions with 3rd party APIs. Specifically for this use case, MailChimp.

### Scenario
Admin needs to be able to dynamically map which form fields will feed into MailChimp upon form submission. This does need to be dynamic as it will vary from form to form. Submissions will feed into specific MailChimp lists, groups, segments, or list sources on a per-form basis. Not sure on current set of MailChimp features, but at a minimum a list will be needed.

After the visitor submits the form on the website, the entry will be logged in coderedcms as usual, and the user will now be opted in to a mailchimp list.

### Implementation
Ideally some kind of dynamic API integration mechanism would be nice as part of the form page. But this might not be possible or be too difficult to implement. I'm fine with doing a mailchimp-specific feature. This could be an isolated component/package that uses a hook on form submit. Or it could be something baked into the form page. Not sure what is best, although I like the idea of using a hook.

From the technical standpoint, it needs to be fail safe so as not to bomb out or cause data loss if the API call fails. We still need to collect the form submission and notify an admin, rather than bubble this error up to the visitor. Perhaps building in some logging would be good for troubleshooting in different environments which could experience issues caused by IP whitlisting or domain verification.

From the admin UX standpoint, I envision this working similar to the CofirmationEmails, which uses the Django templating engine to map form submission fields within a context. That could be useful for rendering a JSON or POST payload to an API endpoint. Similar to ConfirmationEmails, maybe we have an ApiCall streamfield which takes a URL, an http method, and a payload to post (which gets rendered with the context).

**Comment by corysutyak** [comment]
Implement an Integrations tab.  The integrations are a model that has a `ParentalKey` to the form page.  The user will be able to add Integrations on the fly.  For the MailChimp integration, the model will have a dropdown for the list you want to send the data to.  Ideally, it will also display fields for each field in the MailChimp list for the user to enter in their form variable.  When form is submitted, a hook will get triggered and all the integrations should run under that hook.
