### ISSUE TITLE
Nav bar model should be orderable

### ISSUE THREAD

**Issue by thenewguy** [coderedcorp/coderedcms#377]
It would be helpful if the [navbar model](https://github.com/coderedcorp/coderedcms/blob/dev/coderedcms/models/snippet_models.py#L217) inherited from Orderable so it was easy to control the order in which they are rendered for styling purposes

**Comment by vsalvino** [comment]
This will be addressed as part of the refactor for #251 ... Please add any additional comments on that thread.
