### ISSUE TITLE
Nav bar option for wrap

### ISSUE THREAD

**Issue by thenewguy** [coderedcorp/coderedcms#378]
It seems that the default style on the navbar is `flex-wrap: nowrap`.  It would be nice (or maybe preferrable to wrap): `flex-wrap: wrap`

Is it intentional for the navbar not to wrap by default?  Adding wrap allows creative use of bootstrap styles in the admin for positioning

-- edit -- this is referencing the [element with the id #navbar]( https://github.com/coderedcorp/coderedcms/blob/dev/coderedcms/templates/coderedcms/snippets/navbar.html#L27)

**Comment by vsalvino** [comment]
Those classes are built-in to Bootstrap. We try to avoid any changes to default bootstrap styles, unless absolutely necessary. The recommended approach is to create your own navbar HTML template as needed (which almost all of our sites have, in practice). I think we could improve the built-in navbar HTML template a bit though to add more blocks and enable easier overriding.

**Comment by thenewguy** [comment]
@vsalvino bootstrap offers control over flex-wrap per https://getbootstrap.com/docs/4.5/utilities/flex/#wrap

**Comment by thenewguy** [comment]
Would you be okay with making extra classes on that element a template block and handled via #379
