### ISSUE TITLE
Google Tracking UA- and G- instrumentation

### ISSUE THREAD

**Issue by thenewguy** [coderedcorp/coderedcms#384]
New Google Tracking IDs seems to start with "G-" but the help text says "UA-"

**Comment by vsalvino** [comment]
Looks like they have both... and they are *slightly* different. I think the solution would be to appropriately support all three types (gtag, analytics, google tag manager).

https://developers.google.com/analytics/devguides/collection/ga4/basic-tag?technology=gtagjs
