### ISSUE TITLE
str has no attr 'DoesNotExist' when passing random search_model argument as /search/?s=keyword&t=t

### ISSUE THREAD

**Issue by adminBTI** [coderedcorp/coderedcms#387]
#### Passing random search_model argument as /search/?s=keyword&t=t
Hackers are scanning Codered websites by passing random args for parameter t like this:
 /search/?s=keyword&t=t

This dumps error: 'str' object has no attribute 'DoesNotExist'

I believe this is coming from lib/python3.7/site-packages/coderedcms/views.py
Can we replace **except search_model.DoesNotExist:**
by just **except**
or by, **except ContentType.DoesNotExist:**

**Comment by vsalvino** [comment]
First of all - friendly reminder to **always use DEBUG=False** in your settings on any live site to ensure that if an error does occur, it will not dump any stack trace or technical information.

Yes, that does look like a bug. Would you be willing to make a pull request to fix?

**Comment by vsalvino** [comment]
CC @rcoldiron - if a PR does not come through for this issue in a few days, could you please implement the bug fix?
