### ISSUE TITLE
Django Tenant Support

### ISSUE THREAD

**Issue by saileshkush95** [coderedcorp/coderedcms#392]
Thank you for this amazing project. 

But I think this project would be awesome if it support django tenants.

**Comment by vsalvino** [comment]
I don't see any reason why it couldn't. I don't think you would need us to make any changes... from looking at Django Tenants you should be able to integrate it with coderedcms/wagtail as usual.

**Comment by saileshkush95** [comment]
I just tried it it is working fine, but I need little bit tweak to make it work perfectly, because I'm using to admin panel one for tenant and another for public which control all the tenants. Now I can add edit or delete tenants directly using wagtails admin.
