### ISSUE TITLE
Drag and Drop theme installation.

### ISSUE THREAD

**Issue by saileshkush95** [coderedcorp/coderedcms#394]
#### Additional context

By default this is awesome, but do we have any plans to integrate, drag and drop themes installation. Just like wordpress.  So that we can design and develop themes more freely instead of overriding the templates.

**Comment by vsalvino** [comment]
Drag and drop themes would be unlikely. Most likely themes will be implemented as a pip package, which can be installed and specified in the django settings. All theme-related discussion is taking place in #44
