### ISSUE TITLE
Auto download uses jquery before it is available

### ISSUE THREAD

**Issue by thenewguy** [coderedcorp/coderedcms#397]
Just noticed that the auto download button outputs javascript that uses jquery before jquery is available.

I see this error in the console:
```
Uncaught ReferenceError: $ is not defined
```

Jquery is included and used on the page.  I am guessing this is a timing issue with where the javascript is output in the page templates.

Is this working for everyone else?  Otherwise I guess it needs some tweaking.  If using jquery is the best way for this feature, perhaps using an interval that waits for jquery to be available.

**Comment by vsalvino** [comment]
Closing this as automatic download was removed in 1.0
