### ISSUE TITLE
`generate_random_id` template tag produces invalid id

### ISSUE THREAD

**Issue by thenewguy** [coderedcorp/coderedcms#398]
I've been tracking down a strange issue where modals would randomly not work.  The frustrating part was the same modal that failed would work after refreshing the page.

This is what I have come up with:

[generate_random_id](https://github.com/coderedcorp/coderedcms/blob/a0dd8e9a48ec7141ce8beb87d0113a6c281e15f6/coderedcms/templatetags/coderedcms_tags.py#L42) does not produce a valid html id.  This breaks bootstrap modals.

Per https://www.w3.org/TR/html401/types.html#type-name id must start with a letter `[A-Za-z]`.

Simple fix would be to prepend something like 'cr-' to the id

**Comment by vsalvino** [comment]
Good catch, and thanks for the PR
