### ISSUE TITLE
Get IPv4 address (or IPv6 address) that submitted the Form?

### ISSUE THREAD

**Issue by adminBTI** [coderedcorp/coderedcms#405]
How to get the IPv4/IPv6 address of the user who submitted the form?

**Comment by vsalvino** [comment]
Currently, we do not store that by default. I think it would be a good enhancement to store this though. IP address would have to come from the request object's HTTP headers while processing the POST. See: https://docs.djangoproject.com/en/3.1/ref/request-response/

I would be happy to merge a pull request if you feel like implementing it, to store IP address on all form submissions.

**Comment by adminBTI** [comment]
Where should I insert

request.headers.get('User-Agent')
request.headers.get('Remote-Addr')

Some form dictionary to add (k,v) to?

**Comment by vsalvino** [comment]
You would have to extend the Form Submission class. Currently we are using the one provided from `wagtail.contrib.forms`, however it would be possible to replace this with our own which has a field for IP address.

See: https://github.com/coderedcorp/coderedcms/blob/49673f2bec0ad70f3ea2e04b32a5fce9e63cb916/coderedcms/models/page_models.py#L1424

and

https://github.com/coderedcorp/coderedcms/blob/49673f2bec0ad70f3ea2e04b32a5fce9e63cb916/coderedcms/models/page_models.py#L1390

**Comment by adminBTI** [comment]
Can I just append self.request.get('REMOTE_ADDR') in function send_summary_mail(self, request, form, processed_data) ?

**Comment by vsalvino** [comment]
Yes, you definitely could do that to get the IP in the email (but it would not be saved to the form submission).

**Comment by murty2** [comment]
In order of preference, client IP is in the values of these header fields:
 'HTTP_X_REAL_IP', 'HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR'

Therefore, I edited as follows the file: coderedcms/lib/python3.*/site-packages/coderedcms/models/page_models.py. It works :)
```
--- page_models.py.orig 2021-06-22 15:33:24.311084125 -0400
+++ page_models.py      2021-06-22 15:33:01.889686894 -0400
@@ -1278,6 +1278,11 @@
 
         content = '\n------------------- \n'.join(content)
 
+        content += '\n\nSent via {0}'.format(request.META['HTTP_REFERER'])
+        for i in ['HTTP_X_REAL_IP', 'HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR']:
+            if i in request.META:
+                content += '\n{0}: {1}'.format(i, request.META[i])
+
         # Build email message parameters
         message_args = {
             'body': content,
```

**Comment by vsalvino** [comment]
You do not need to edit coderedcms to make this happen. You can override the `send_summary_email` function on your `FormPage` model, until this feature is officially added.

https://github.com/coderedcorp/coderedcms/blob/49673f2bec0ad70f3ea2e04b32a5fce9e63cb916/coderedcms/models/page_models.py#L1266

For example, in `website/models.py`:

```python
class FormPage(CoderedFormPage):
    ...

    def send_summary_mail(self, request, form, processed_data):
        # Copy contents from coderedcms below, then edit with your patch.
```
