### ISSUE TITLE
How can i override footer streamfield?

### ISSUE THREAD

**Issue by saileshkush95** [coderedcorp/coderedcms#406]
Is there any simple way to override stream field for footer.

**Comment by vsalvino** [comment]
Unfortunately no - that is a problem due to issue #56 . Please follow along in that issue.

What I would recommend is implementing your own footer snippet, and override `web_page_notitle.html` template to render it in the `<footer>`

**Comment by saileshkush95** [comment]
I didn't find code code snippets for footer. Can you please help me to figure out?
