### ISSUE TITLE
Use of embeds for e-commerce integration

### ISSUE THREAD

**Issue by thenewguy** [coderedcorp/coderedcms#407]
Related to #38 

An idea that keeps coming to me for this is the use of wagtail's embeds feature for integrating with any e-commerce app.

For example, add an embed block named "product" to the `PriceListBlock()` and `PriceListItemBlock()`.  The integration can override the template to make use of this embed for rendering the result.  No work to be done and any e-commerce project can be used.

Then we just require the e-commerce package to provide an oEmbed endpoint that gives json data about the project and render using something like `{{ self.product.price }}`.  ([a custom embed finder can be written as a 3rd party app to integrate with provider apis](https://docs.wagtail.io/en/stable/advanced_topics/embeds.html#custom-embed-finder-classes))

For example, pseudo-template code in a projects customized template:

```
{% if self.product %}

<strong class="leaders"><span>{{self.product.name}}</span><span><s>{{ self.product.msrp }}</s>{{ self.product.sale_price }}</span></strong>

<p>{{self.description}}</p>

<a href="{{ self.product.add_to_cart_link }}">Add to cart</a>

{% else %}

<strong class="leaders"><span>{{self.name}}</span><span>{{self.price}}</span></strong>

<p>{{self.description}}</p>

{% endif %}
```

I don't really think there is much that could be lacking with this approach.  Plus, wagtail already ships the code to make it possible.

Some blocks could use additional template to ease extension for integrations, but overall this seems simple and straightforward to me.

The same concept would work for a default Product Page if you wanted to ship one.  But it seems simple enough to add at the integration level at first

**Comment by vsalvino** [comment]
From my understanding, there would be nothing required in coderedcms directly to accomplish this. Our embed block (Embed Media) is already just a wrapper around Wagtail's Embed, and can be used anywhere in the streamfield (or you can customize your page body/streamfield to include it where you want specifically).

The only limiting factor would be the embed provider, e.g. adding an embed for Amazon or Shopify. But this embed finder should probably live in a separate pip package.

**Comment by thenewguy** [comment]
Correct, other than adding `product = EmbedBlock()` in the appropriate blocks like `PriceListBlock()` and `PriceListItemBlock()`

**Comment by vsalvino** [comment]
The PriceList block is often used for restaurant menus, service providers, etc., so that is too specific a use-case to be included in that specific block. I would recommend you create your own block in your project, then add it to your page's streamfield where needed. Please report back if you end up building an oembed provider!
