### ISSUE TITLE
Form page email strings should be templatable

### ISSUE THREAD

**Issue by thenewguy** [coderedcorp/coderedcms#413]
The help text for "reply-to" address states: 

> Optional - to reply to the submitter, specify the email field here. For example, if a form field above is labeled "Your Email", enter: {{ your_email }}

It would be very helpful if the form submission "subject" could be templated with form data as well.  This would allow adding the persons name or email address to the subject line to prevent email clients from grouping unrelated submissions (i.e. gmail will collapse all of the submissions into one chain without a unique string in the subject per submission)

Also, the confirmation email fields should have this template formatting - ideally for subject and body in addition to the "to address".  Right now, it doesn't seem possible to use the captured email address for sending the confirmation email.  I get this error: `(554, b"Transaction failed: Empty required header 'To'.")`.  The form field label is set as `Email` and the `To Address` on the confirmation was set to `{{ email }}` per the help text quoted above.

-- edit --

[So I see the context is being rendered for these fields](https://github.com/coderedcorp/coderedcms/blob/2a6dfd648669ee287ad708f7cfb6c798da051ca5/coderedcms/models/page_models.py)

Is the problem a case issue?

**Comment by thenewguy** [comment]
Going to close this until I can figure out why the template isn't working

**Comment by vsalvino** [comment]
This is not well documented, but the fields names are slugified. So for example if you have a field named "Your Email", the corresponding context entry would be called `{{ your_email }}`

**Comment by thenewguy** [comment]
@vsalvino I have not been able to get it to work.  Am I doing anything obviously wrong?  Is there a form prefix in the data?  I don't see an easy way to email the context along for debugging.

I configured the email label as above.

![your-email](https://user-images.githubusercontent.com/77731/113772563-d97c8300-96f2-11eb-904d-bf20f9156342.png)

I configured the form submission result email:

![form-submission-config](https://user-images.githubusercontent.com/77731/113773854-886d8e80-96f4-11eb-8fa8-968cd6d85a6a.png)

I configured the form confirmation email:

![confirmation-email](https://user-images.githubusercontent.com/77731/113773890-91f6f680-96f4-11eb-8558-a7d2b27d3247.png)

I submitted the form:

![form-submission](https://user-images.githubusercontent.com/77731/113773906-991e0480-96f4-11eb-90a0-8875465abc59.png)


I did not receive a confirmation email and this is the subject sent with the form submission:

![result-subject](https://user-images.githubusercontent.com/77731/113773943-a5a25d00-96f4-11eb-9bde-ad488da7d65b.png)
