### ISSUE TITLE
Form page confirmation_emails field template strings

### ISSUE THREAD

**Issue by thenewguy** [coderedcorp/coderedcms#414]
I have been attempting to get form page confirmation_emails working.  However, the templates do not seem to be rendering as expected.

Can anyone confirm they are able to set the "to address" to an email address captured in the form data?  Can you share the email address field label and how it is written in your template string?

[The code reads like it should work](https://github.com/coderedcorp/coderedcms/blob/2a6dfd648669ee287ad708f7cfb6c798da051ca5/coderedcms/models/page_models.py), but I am not finding tests to compare against and have been unsuccessful in my attempt to send confirmation emails.  If I hardcode the email address, it works fine, but I cannot template any of the other fields.

I end up with this error in the logs:
```
(554, b"Transaction failed: Empty required header 'To'.")
```

**Comment by vsalvino** [comment]
This is not well documented, but the fields names are slugified. So for example if you have a field named "Your Email", the corresponding context entry would be called {{ your_email }}.

I would caution this practice though, because if a spammer starts hitting your form they could abuse it to dynamically send malware/spam to recipients from your website form. I have seen this happen in some cases. Just make sure if you do dynamically use the email address, the message is static (e.g. a confirmation email) and not also dynamically filled from the form.

**Comment by thenewguy** [comment]
Sorry for two email chains - quoting my previous comment here since this is the open issue and tagging https://github.com/coderedcorp/coderedcms/issues/413

> @vsalvino I have not been able to get it to work. Am I doing anything obviously wrong? Is there a form prefix in the data? I don't see an easy way to email the context along for debugging.
> 
> I configured the email label as above.
> 
> ![your-email](https://user-images.githubusercontent.com/77731/113772563-d97c8300-96f2-11eb-904d-bf20f9156342.png)
> 
> I configured the form submission result email:
> 
> ![form-submission-config](https://user-images.githubusercontent.com/77731/113773854-886d8e80-96f4-11eb-8fa8-968cd6d85a6a.png)
> 
> I configured the form confirmation email:
> 
> ![confirmation-email](https://user-images.githubusercontent.com/77731/113773890-91f6f680-96f4-11eb-8558-a7d2b27d3247.png)
> 
> I submitted the form:
> 
> ![form-submission](https://user-images.githubusercontent.com/77731/113773906-991e0480-96f4-11eb-90a0-8875465abc59.png)
> 
> I did not receive a confirmation email and this is the subject sent with the form submission:
> 
> ![result-subject](https://user-images.githubusercontent.com/77731/113773943-a5a25d00-96f4-11eb-9bde-ad488da7d65b.png)

**Comment by vsalvino** [comment]
From looking at the code (https://github.com/coderedcorp/coderedcms/blob/2a6dfd648669ee287ad708f7cfb6c798da051ca5/coderedcms/models/page_models.py#L1266) it looks like the admin notification email does not render any fields as django templates, meaning you cannot fill any fields in those.

However the confirmation emails render all fields as templates. Please try by setting your django email backend to console and view the output form runserver to confirm the email is formatted as expected.
