### ISSUE TITLE
Upgrade to Bootstrap 5

### ISSUE THREAD

**Issue by Correct-Syntax** [coderedcorp/coderedcms#417]
#### Is your feature request related to a problem? Please describe.
Boostrap 5 is now released (https://blog.getbootstrap.com/2021/05/05/bootstrap-5/). Boostrap 5 is the future and with so many breaking changes, you really need to upgrade (I realize that's easier said-than-done!) Keep up the good work!

#### Describe the solution you'd like
Implement Bootstrap 5

#### Describe alternatives you've considered
Wait.... 😄

**Comment by adminBTI** [comment]
Bootstrap 5 is much cleaner and better than Bootstrap 4. One can create a fully self-hosted website without jquery and fontawesome. I personally believe that BS5 will proved to be a revolution leading to a whole new generation of fast websites, whether in Wordpress or Django.

It would be awesome if Codered supports BS5 soon :)

**Comment by vsalvino** [comment]
This will be a major undertaking and will result in a new major version of coderedcms (probably 1.0 hopefully!)  As such we would move the current bootstrap 4 templates to a pip package, as a theme for backwards compatibility.

We would also need to evaluate switching from django-bootstrap4 to django-bootstrap5 once that project is ready. https://github.com/zostera/django-bootstrap5

**Comment by ashwin31** [comment]
Hi @vsalvino 
They are saying that it's production ready per ther readme.md https://github.com/zostera/django-bootstrap5

Do we have any progress or ETA on this topic?

**Comment by vsalvino** [comment]
Upgrading to bootstrap 5 will be a huge effort for us... we don't have the work scheduled yet but it will probably happen during the first quarter of 2022. If anyone wants to get started feel free to make pull requests, I will start a `bootstrap5` branch which any PRs can go into as a work in progress.
