### ISSUE TITLE
How to change slug and sitemap missing

### ISSUE THREAD

**Issue by Mayanktaker** [coderedcorp/coderedcms#419]
I am trying to make a site with this awesome CMS. So far its excellent. But missing Sitemap and comment feature.
One problem I am facing is that the slug is auto generating in my Hindi language for my Hindi blog site. But when I am sharing it to social media, its showing long %%%% characters because of unicode. 
I want to change the slug to generate the post date and year wise or if possible like in Django(AutoSlug), convert the slug to English.

**Comment by vsalvino** [comment]
The simplest approach might be to use Wagtail's `WAGTAIL_ALLOW_UNICODE_SLUGS=False` setting, which will only use ASCII (English) characters in the slugs.

https://docs.wagtail.io/en/v2.11.7/reference/settings.html#unicode-page-slugs

To customize the slug generation, you may need to override the `full_clean` method of the page model: https://github.com/wagtail/wagtail/blob/afd707f6b40e63faaccbd743bdc0fc2111af0043/wagtail/core/models.py#L429

**Comment by Mayanktaker** [comment]
Hi. When I use the `WAGTAIL_ALLOW_UNICODE_SLUGS=False `base.py, 
I  am getting `blog/-----------------------/` 
I am not putting slug manually and leaving it blank for the post.

**Comment by vsalvino** [comment]
Can you test this same feature out on a plain wagtail site, and report back? For example, run wagtail start, set the unicode setting, then enter some pages in the admin and see if the behavior is the same.
