### ISSUE TITLE
og_image templatetag invalid url when image model returns a complete url

### ISSUE THREAD

**Issue by thenewguy** [coderedcorp/coderedcms#421]
This is similar to #240 and the same solution to that problem can be applied to this issue.

The base url is output twice when the image model returns a url that include the domain it should be served from.  Serving images from their own domain is a common practice.  The fix here is simple:

[og_image](https://github.com/coderedcorp/coderedcms/blob/49673f2bec0ad70f3ea2e04b32a5fce9e63cb916/coderedcms/templatetags/coderedcms_tags.py#L48):

```
@register.simple_tag(takes_context=True)
def og_image(context, page):

    # Fixes #240 https://github.com/coderedcorp/coderedcms/issues/240
    # Prepend the site's root URL except for when MEDIA_URL already
    # looks like a full URL.
    protocol = re.compile(r'^(\w[\w\.\-\+]*:)*//')

    if protocol.match(settings.MEDIA_URL):
        base_url = ''
    else:
        base_url = Site.find_for_request(context['request']).root_url

    if page:
        if page.og_image:
            return base_url + page.og_image.get_rendition('original').url
        elif page.cover_image:
            return base_url + page.cover_image.get_rendition('original').url

    layout_settings = LayoutSettings.for_request(context['request'])
    if layout_settings.logo:
        return base_url + layout_settings.logo.get_rendition('original').url

    return None
```

becomes something like:
```
    # Fixes #240 https://github.com/coderedcorp/coderedcms/issues/240
    # Prepend the site's root URL except for when MEDIA_URL already
    # looks like a full URL.
    protocol_re = re.compile(r'^(\w[\w\.\-\+]*:)*//')

def og_image(context, page):
    url = None

    if page:
        if page.og_image:
            url = page.og_image.get_rendition('original').url
        elif page.cover_image:
            url = page.cover_image.get_rendition('original').url

    if not url:
        layout_settings = LayoutSettings.for_request(context['request'])
        if layout_settings.logo:
            url = layout_settings.logo.get_rendition('original').url

    if url and not protocol_re.match(url):
        url = Site.find_for_request(context['request']).root_url + url

    return url
```

**Comment by vsalvino** [comment]
With django media files, the absolute URL is generally not stored in the database, only the relative path to the file is.

Can you describe the setup of your media that is causing it to return the absolute URL from the rendition?

**Comment by thenewguy** [comment]
The images are served from a different domain than the html

**Comment by vsalvino** [comment]
Generally the domain that is serving images would be stored in `settings.MEDIA_URL`. Are you using AWS S3, or some other product, and can you provide the custom django code you are using that handles the media files? Without this it would be difficult to recreate the issue you are describing.

**Comment by thenewguy** [comment]
Our image model's `url` property returns a fully qualified url.  Using an AWS S3 storage backend for images would be another way to have fully qualified image urls on a different domain

**Comment by thenewguy** [comment]
If you mean for testing, a mock on the Image.url property that returns a full url should trigger the issue

**Comment by thenewguy** [comment]
Would you like me to write a failing testcase?

**Comment by vsalvino** [comment]
Ah I see, that makes sense if you override the Image model's default `url` behavior.

You can probably implement a fix by matching `protocol_re` against the image URL before joining any other URLs. If you'd like to make a pull request, please do so in [`wagtail-seo`](https://github.com/coderedcorp/wagtail-seo) as that will be replacing this functionality soon. The code should look familiar as it was based on coderedcms :)

**Comment by thenewguy** [comment]
Sounds good.  Would you like to use `urljoin` and just rely on the standard library to do the right thing?

**Comment by thenewguy** [comment]
I just looked through wagtail-seo - looks awesome! I think this issue is already handled by https://github.com/coderedcorp/wagtail-seo/blob/c2d54d1136f84dc80da971936b5281997afbecef/wagtailseo/utils.py#L46
