### ISSUE TITLE
Remove SocialMedia Settings

### ISSUE THREAD

**Issue by Mayanktaker** [coderedcorp/coderedcms#424]
I want to add more social media accounts in the same SOCIAL MEDIA ACCOUNTS page. I want to add WhatsApp, telegram etc linsk. How can I modify and add more accounts under Social Media settings?

**Comment by vsalvino** [comment]
This is a great question. The social media settings are actually not used in coderedcms by default (except for opengraph tags, which are being replaced by [wagtail-seo](https://github.com/coderedcorp/wagtail-seo).

I think we would be inclined to remove those settings in a future version. In most sites we have seen, the social media links are manually added to the footer or navbar. I would recommend for the time being that you manually add your links to the site content as needed.

**Comment by vsalvino** [comment]
I am labeling this with needs research and tech debt, because the current incarnation of social media settings do nothing. These should either be re-implemented to be useful, or removed.

**Comment by vsalvino** [comment]
Making the decision to delete SocialMediaSettings, and any references to them. They are not used natively by coderedcms. Be sure to note this in the release notes as a breaking change. If a site is using them for some custom purpose, then they should re-implement their own site settings model and use that instead.

**Comment by Mayanktaker** [comment]
I support the removal but if you are building site for client and they want to change or add by themself then its not good to give them access tot he footer html code to add/change the links.
