### ISSUE TITLE
Form fields validation

### ISSUE THREAD

**Issue by plascual** [coderedcorp/coderedcms#452]
Hi!

I would like to add a new field type to FormPages.

There are currently many field types, but I would like to add a regex field type validation. For example, integer-only field type with regex validation.

Do I need to override existing code?

**Comment by vsalvino** [comment]
This should be relatively easy to accomplish... 

First implement your own FormBuilder, which inherits from CoderedFormBuilder (coderedcms.forms). See the code in forms.py for an example of how to do this, and how to add your own custom fields. Then extend enhance FormPageField ni your models.py to add the choices to your new fields.

Then on your FormPage, set the builder to your custom builder.

e.g.
```python
from django import forms
from coderedcms.forms import CoderedFormBuilder, FORM_FIELD_CHOICES
from coderedcms.models import CoderedFormPage

class MyField(forms.CharField):
    # Custom logic here, as with a regular Django form field.
    ...

class MyFormBuilder(CoderedFormBuilder):
    # Add custom fields here
    def create_myfield_field(self, field, options):
        return MyField(**options)

class FormPage(CoderedFormPage):
    form_builder = MyFormBuilder

class FormPageField(CoderedFormField):
    field_type = models.CharField(
        verbose_name=_('field type'),
        max_length=16,
        choices=FORM_FIELD_CHOICES + [('myfield', 'My Custom Field')],
        blank=False,
    )
```

See: https://github.com/coderedcorp/coderedcms/blob/dev/coderedcms/forms.py
