### ISSUE TITLE
CODERED_BANNER does not appear in the CMS

### ISSUE THREAD

**Issue by James-Osgood** [coderedcorp/coderedcms#457]
#### Describe the bug
The [`CODERED_BANNER` setting](https://docs.coderedcorp.com/cms/reference/django_settings.html#codered-banner) is not applied to the Wagtail CMS.

#### Steps to reproduce
1. Add `CODERED_BANNER = "Test"` to `settings/base.py`
2. Start the server.
3. Sign into the CMS (default is `admin/`).

#### Expected behavior
A light yellow banner at the top of the screen with the text "Test".

#### Additional context
It looks like the CMS banner was removed in #226 with the deletion of the `base.forked.html` template. If this was intentional, then the docs should be updated.

Otherwise, it looks like it would be difficult to add the banner in an appropriate place to the CMS without overriding the base Wagtail admin template again or adding some JavaScript.

**Comment by vsalvino** [comment]
I don't think this removal was intentional. If you're able to make a pull request with the fix that would be appreciated :)

**Comment by James-Osgood** [comment]
Sure. I'll put a PR together to add the banner back.

**Comment by vsalvino** [comment]
Closed via #459
