### ISSUE TITLE
Importing an ICS file into "The New Outlook for Mac" gets stuck trying to sync to the living version of the event

### ISSUE THREAD

**Issue by rcoldiron** [coderedcorp/coderedcms#467]
Note: this only happens on "The New Outlook for Mac", not the previous version.

When you download an ICS file from an event page and upload it to Outlook, the event does not fully sync to the calendar. According to my research, this is default by Microsoft. 

- When a calendar is imported into Outlook via an ICS file, the event will not be synced to the Cloud.
- "Note: When you import an .ics file, your calendar doesn't refresh the imported events, even if the calendar's owner makes an update." - https://support.microsoft.com/en-gb/topic/cff1429c-5af6-41ec-a5b4-74f2c278e98c 
- Syncing allows for editing of an event. Because the event comes from someone else's calendar (ie the website where you downloaded the event), Outlook for Mac wants to sync to the calendar it came from but can't since the file is a static copy of the event. However, you can still delete an imported event from your own personal calendar.
- "### The difference between importing and subscribing to a calendar
When you import an .ics file, you get a snapshot of the events in the calendar at the time of import. Your calendar doesn't refresh the imported events automatically -- even if the calendar's owner makes an update. This is a good way to add events to your existing calendar that aren't going to change, like tide tables or phases of the moon.
Subscribing to an online calendar connects it to your calendar. Whenever the owner of a calendar you've subscribed to makes changes to the events, Outlook.com updates your calendar. This is a good way to track events that change frequently, like movie times or a school calendar." https://support.microsoft.com/en-gb/topic/cff1429c-5af6-41ec-a5b4-74f2c278e98c 
- Maybe we should allow for subscribing to the website's calendar or event to receive updates and sync instead of downloading an ICS file, or allow for both options. Subscribing still does not permit an outside user to edit someone else's event but it will refresh the event if info changes.

**Comment by vsalvino** [comment]
So the customer-facing issue is not related to syncing. The issue is that certain information, such as the location, does not appear or is not editable.

In this case, we want to make sure our ICS file is set up to NOT sync (i.e. "import" mode, not sync mode). It might be the case that outlook is trying to sync, based on some parameter in the ICS file, in which case we should remove that parameter.
