### ISSUE TITLE
Shuttering Peregrine: useful features?

### ISSUE THREAD

**Issue by FlipperPA** [coderedcorp/coderedcms#47]
Hey team,

I'm thinking about shuttering Peregrine and putting my efforts here so we're not duplicating a lot of effort, and y'all are farther along than me: https://github.com/flipperpa/peregrine/

There are a few features I think would be worth implementing here that are already completed in Peregrine, and wanted your feedback before I started working:

- embeds with automatic Bootstrap 4 size detection has worked really well in practice: https://github.com/FlipperPA/peregrine/blob/master/peregrine/templates/wagtailembeds/embed_frontend.html
- ability to only keep a certain number of revisions from a setting: https://github.com/FlipperPA/peregrine/blob/master/peregrine/wagtail_hooks.py#L22
- integration with Wagtail Code Block, for consistent syntax highlighted code blocks both in the editor and front end

Do these three sound like PRs that would be worth putting together? Great work, as always!

**Comment by vsalvino** [comment]
Thanks for getting so involved! I really appreciate all the effort you've been sharing with us :)

* Bootstrap 4 embeds: I like what you've done. We actually should probably remove our "embed video" block and replace it with wagtail's native EmbedBlock, which is much more robust, and then extend the default EmbedBlock template to use Bootstrap4 styling. I like how you detect content sizes. I will create an issue for this describing what needs to happen.
* For revision history, I would be inclined to not include this in CodeRed CMS. Something like this would probably be better implement on a project-by-project basis.
* There is already an issue for the code block. I think the solution here is that we will remove our Formatted Code Block from the default streamfield, and provide a way or a hook of some sort to easily add blocks in a la carte. At that point you would be able to pull in any block from any pip package.
