### ISSUE TITLE
wagtail admin menu breaks when adding more menu items

### ISSUE THREAD

**Issue by tekanokhambane** [coderedcorp/coderedcms#475]
Hi I just installed the latest version and installed other apps which appear in the admin menu but the settings menu gets hidden, how can I fix this?

![codered](https://user-images.githubusercontent.com/33482654/161088130-340d33c2-2205-43d5-a83f-bbbae768ff22.png)

**Comment by vsalvino** [comment]
I think this should be fixed in the `dev` branch by #483 . If possible could you test your project locally installing coderedcms from the `dev` branch? This change should go out in the next release (0.23)

**Comment by vsalvino** [comment]
Can you confirm that this issue is fixed in version 0.23?

**Comment by vsalvino** [comment]
Closing this issue as it is no longer relevant as of recent releases. We are now using the stock Wagtail admin. If there are any future bugs regarding layout of the side menu, please report those directly to Wagtail.
