### ISSUE TITLE
Expected UI issues with Wagtail 3.0 release

### ISSUE THREAD

**Issue by thibaudcolas** [coderedcorp/coderedcms#479]
Hi CodeRed Extensions! The [Wagtail 3.0 first release candidate](https://github.com/wagtail/wagtail/discussions/8362) is out. There are large UI changes in this release, for which we have [reviewed expected breakage in third-party UI customisations](https://github.com/wagtail/wagtail/discussions/7739#discussioncomment-2615089).

This is beyond what we do with our normal breaking changes policy, since the majority of those changes are on parts of Wagtail that haven’t been publicly supported / documented in any way. To make sure this goes smoothly anyway, I’m here to provide an advance notice of what we’re aware of with this specific package 🙂 

In the case of CodeRed there are two changes we’re expecting to require rework for Wagtail 3.0.

## Uppercase text

The majority of the Wagtail admin UI [no longer uses uppercase text](https://github.com/wagtail/wagtail/issues/7624), to improve readability. The exception is the page status (live, draft, etc.). Suggested actions:

- Remove all usage of uppercase text in the CMS, except for page status.
- Aside from CSS, the utility classes `u-text-transform-uppercase` and `label-uppercase` no longer exist and shouldn’t be used anymore.

Here are matches in this repository, some of which (docs, tutorial, site template) are likely false positives:

```text
wagtail/coderedcorp/coderedcms/tutorial/mysite/website/static/website/css/custom.css
4:    text-transform: uppercase;

wagtail/coderedcorp/coderedcms/coderedcms/static/coderedcms/css/codered-editor.css
157:    text-transform: uppercase;
247:    text-transform: uppercase;

wagtail/coderedcorp/coderedcms/coderedcms/static/coderedcms/vendor/bootstrap/dist/css/bootstrap.css
455:  text-transform: uppercase;
10076:  text-transform: uppercase !important;

wagtail/coderedcorp/coderedcms/coderedcms/static/coderedcms/vendor/bootstrap/scss/utilities/_text.scss
31:.text-uppercase  { text-transform: uppercase !important; }

wagtail/coderedcorp/coderedcms/coderedcms/static/coderedcms/vendor/bootstrap/scss/_type.scss
108:  text-transform: uppercase;

wagtail/coderedcorp/coderedcms/docs/advanced/advanced01.rst
223:        text-transform: uppercase;
320:        text-transform: uppercase;

wagtail/coderedcorp/coderedcms/docs/_static/docs.css
156:    text-transform: uppercase;
```

From what I can see here, I’d expect only `codered-editor.css` needs rework.

## Core templates reuse

From this list, it’s the extends of `wagtailadmin/base.html` I would expect need a second look. We haven’t made may changes to this base template, but it’s worth checking.

```text
wagtail/coderedcorp/wagtail-cache/wagtailcache/templates/wagtailcache/index.html
1:{% extends "wagtailadmin/base.html" %}
7:    {% include "wagtailadmin/shared/header.html" with title=title_str icon=cache_icon %}

wagtail/coderedcorp/coderedcms/coderedcms/templates/wagtailadmin/home.html
1:{% extends "wagtailadmin/home.html" %}

wagtail/coderedcorp/coderedcms/coderedcms/templates/wagtailadmin/base.html
1:{% extends "wagtailadmin/base.html" %}

wagtail/coderedcorp/coderedcms/coderedcms/templates/wagtailadmin/login.html
1:{% extends "wagtailadmin/login.html" %}

wagtail/coderedcorp/coderedcms/coderedcms/templates/wagtailimportexport/index.html
1:{% extends "wagtailadmin/base.html" %}
6:    {% include "wagtailadmin/shared/header.html" with title=title_str icon="download" %}

wagtail/coderedcorp/coderedcms/coderedcms/templates/wagtailimportexport/import_from_csv.html
1:{% extends "wagtailadmin/base.html" %}
14:    {% include "wagtailadmin/shared/header.html" with title=title_str icon="download" %}
21:                    {% include "wagtailadmin/shared/field_as_li.html" %}
32:    {% include "wagtailadmin/pages/_editor_js.html" %}
```

---

I hope this all makes sense. We’ve made a lot of other styling and template changes that are hard to track down, and for which it’s unclear whether any breakage might be expected or not. As you go through the Wagtail 3.0 compatibility work, please let me know if there are other compatibility issues you come across so we can consider those customisations in Wagtail development in the future, and let others know about those breakages.

**Comment by vsalvino** [comment]
Excellent!!! Thank you for doing this Thibaud, it will be a big help!
