### ISSUE TITLE
CoderedCMS/Wagtail  Admin Page Issue

### ISSUE THREAD

**Issue by ashrafZolkopli** [coderedcorp/coderedcms#488]
#### Describe the bug
I just migrate my application to server. while my old coderedcms does not seem to have this problem, I found that on my production server the admin page seem broken

![image](https://user-images.githubusercontent.com/59853680/168751439-d37fd3b4-e736-4c5a-b809-a3345648657d.png)

#### Expected behavior
I expect the same admin page as in my localhost
![image](https://user-images.githubusercontent.com/59853680/168751586-c43569c2-42f2-4f10-8492-afac75474e31.png)

#### Additional context
I just deploy this application last weekend

**Comment by vsalvino** [comment]
It looks like some CSS is missing. Can you confirm a few things:

* Version: run `pip show coderedcms` on both local and on server. Do the versions match?
* On your server did you run: `python manage.py collectstatic`?
* Can you open the browser dev tools, in the network tab, and look for any 404s?

**Comment by ashrafZolkopli** [comment]
From what I can gather, Maybe theres a change from version 0.22.3 to 0.23.0?
Should I drop my production server version to 0.22.3 or is there any changes I need to do to make 0.23.0 to work with my current code?

**Comment by ashrafZolkopli** [comment]
Thanks again for your quick respond,

I think I need to update my docker-compose/docker file.

Thanks and I thinks I will close this bug issue for now.
