### ISSUE TITLE
Broken Contributing Guide link

### ISSUE THREAD

**Issue by adremides** [coderedcorp/coderedcms#491]
#### Describe the bug
Broken contributing guide link in README.md

#### Steps to reproduce
1. Click Contributing Guide link

#### Expected behavior
The link should point to [Contributing Guide](https://docs.coderedcorp.com/wagtail-crx/contributing/index.html) instead ~~[Contributing Guide](https://docs.coderedcorp.com/wagtail-crx/stable/contributing/index.html)~~.

**Comment by vsalvino** [comment]
Thanks for reporting. This was related to a broken redirect that occurred with the docs changes. The redirect has been fixed. However we should update the README to point to the canonical URL instead.
