### ISSUE TITLE
Can you consider changing the way this editor works?

### ISSUE THREAD

**Issue by davidjeba** [coderedcorp/coderedcms#494]
By Far this is one of the best editors for Django/Wagtail

I have 70 clients on WordPress
all of them are business owners, they are running shops and stores who have no technical knowledge.

They come to us with these requirements
1.I want a website to be built
2.I want to manage the content by myself without any issues

now i have 2 options
WordPress + Elementor
Wix.com

I tried to propose django/wagtail to enterprise clients who are running chain of their business in 40+ locations
they don't prefer django/wagtail because they feel its too hard for them to operate

[all django developers disagree on this, but for end user its not user friendly yet]

the main tool used here which make the end users life easier is, Elementor plugin
https://elementor.com/features/editor/

Wix is even more intuitive than Elementor

I love Django, i really want people to use django which is more secure and robust
i really want designer/developers to build django based templates on https://themeforest.net/search/django%20template
only 42 templates are there in themeforest. out of which not even 10 are for frontend, most are them are admin templates

**So Here are my requests**
1.Can you build a fluid frontend editing [if possible as an exact clone of https://kepler.app/ ]
2.Can you start selling awesome templates in themeforest and in your website like https://www.wxtemplates.com/
3.Almost every hosting provider has a "Managed WordPress hosting" plan, can you offer "Managed Django Hosting" plans

**Comment by vsalvino** [comment]
I appreciate your enthusiasm and understand all too well your clients' needs.

However, what you are asking for is for us to make an exact clone of another editing app, create an entire theme marketplace, and create an entire hosting platform. In the spirit of open source, I will say: "Please create a pull request with these features and I will merge it in".

We have spent several years creating a managed hosting platform for Django/Wagtail: https://www.codered.cloud/

But I am going to close this issue as what you are asking for is an entire business model. With enough years and enough millions of dollars I'm sure it could all be done.

I would probably recommend your customers to use SquareSpace. Wagtail/Django is not designed for canned websites. It is designed for building custom software, which it seems like your clients do not need.
