### ISSUE TITLE
Snippets don't work in fresh install

### ISSUE THREAD

**Issue by Sodium-Hydrogen** [coderedcorp/coderedcms#522]
#### Describe the bug
After a fresh install of version 1.0.1 when I try to create a snippet (footer in this case) none of the options are saved or render properly.

#### Steps to reproduce
1. Fresh install (`pipenv install coderedcms && coderedcms start app ...`)
2. Log in and add a new snippet. Footer, content wall, and nav bar all have issue.
3. Add any content the widgets don't do anything and can't be fully deleted.

#### Expected behavior
The widgets should properly render and save (even html doesn't seem to save).

#### Additional context
Here is an example screenshot.

![image](https://user-images.githubusercontent.com/42423149/187992996-f14b1a26-f785-4e16-98dc-49cd70b84093.png)

**Comment by vsalvino** [comment]
Thanks for reporting. I am seeing this as well, with Wagtail 3.0.2 installed. It appears to be a javascript error when trying to render the streamfield of the snippet. It is working in Wagtail 3.0.1, so they must have introduced a bug.

![image](https://user-images.githubusercontent.com/13453401/188011079-08c1c83a-4fcc-4fb5-bf7f-64f7211a703b.png)

Can you try installing `wagtail==3.0.1` and hard-refresh the browser, and see if the problem persists?

**Comment by Sodium-Hydrogen** [comment]
The problem is gone with wagtail 3.0.1.

Since this bug is their issue and they already have a pull request I'll go ahead and close this.

**Comment by Sodium-Hydrogen** [comment]
Thanks for the quick response!

**Comment by vsalvino** [comment]
They just released Wagtail 3.0.3 which should fix the issue. Can you report back here if it does not? Thanks.
