### ISSUE TITLE
Upgrade to Wagtail 4.0/4.1

### ISSUE THREAD

**Issue by maver1ck** [coderedcorp/coderedcms#525]
#### Is your feature request related to a problem? Please describe.
New Wagtail 4.0 is out. We could make an update.

#### Additional context
This could be helpful: https://docs.wagtail.org/en/latest/releases/4.0.html

**Comment by htran-ubed** [comment]
I'm running CRX on Wagtail 4.1 with a few changes here https://github.com/htran-ubed/coderedcms-wagtail4.1

**Comment by vsalvino** [comment]
Would you be able to make a pull request here, so it can run against all our unit tests?

**Comment by htran-ubed** [comment]
I made a separate branch for fixing backwards compatibility with wagtail>=3.0,<4.1 and requested a pull.

**Comment by vsalvino** [comment]
Implemented in #556
