### ISSUE TITLE
Reverse for 'add' not found. 'add' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by murty2** [coderedcorp/coderedcms#527]
I am getting the following error when I try to add a new page from Admin page

Reverse for 'add' not found. 'add' is not a valid view function or pattern name.

coderedcms/lib/python3.10/site-packages/coderedcms/templates/coderedcms/widgets/checkbox_classifiers.html, error at line 37

 <a class="button bicolor icon icon-plus" href="{% url 'wagtailsnippets:add' 'coderedcms' 'classifier' %}">

Where should the definition for 'add' be? In one of the urls.py files?

**Comment by keepexploring** [comment]
Hi there, just wondering if you managed to resolve this? I'm observing the same behaviour. Thanks!

**Comment by vsalvino** [comment]
Do you have `wagtail.snippets` in `INSTALLED_APPS` in the Django settings?

**Comment by keepexploring** [comment]
Hi @vsalvino yes, it is in INSTALLED_APPS as "wagtail.snippets"

**Comment by keepexploring** [comment]
<img width="1050" alt="Screenshot 2022-10-26 at 20 00 51" src="https://user-images.githubusercontent.com/19638953/198113519-528be57f-8883-4d41-819b-0cc982f00114.png">

This a screenshot of the error message

**Comment by vsalvino** [comment]
I notice you are using Django 4.1... however CRX does not yet support django 4.1.

Could you try `pip install coderedcms`, which should pull in the correct version of Django (4.0.*). Does that solve the problem?

**Comment by keepexploring** [comment]
<img width="1163" alt="Screenshot 2022-10-26 at 20 27 02" src="https://user-images.githubusercontent.com/19638953/198118493-2d51aada-4e3a-4c23-905d-7394df3cc33e.png">

I updated to Django 4.0.8, but still the issue remains - see above

**Comment by keepexploring** [comment]
Doing a complete fresh install to make sure all the requirements are the right version. Will report back if that works.

**Comment by vsalvino** [comment]
If it does not work, can you run `pip freeze` and post the output here? And also post your `INSTALLED_APPS`.

**Comment by keepexploring** [comment]
aiohttp @ https://files.pythonhosted.org/packages/af/d6/248ad502c6049011e7851e1474dd0a58175895388bed15f7f67dcb9187d9/aiohttp-3.8.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=87f44875f2804bc0511a69ce44a9595d5944837a62caecc8490bbdb0e18b1342
aiosignal @ https://files.pythonhosted.org/packages/3b/87/fe94898f2d44a93a35d5aa74671ed28094d80753a1113d68b799fab6dc22/aiosignal-1.2.0-py3-none-any.whl#sha256=26e62109036cd181df6e6ad646f91f0dcfd05fe16d0cb924138ff2ab75d64e3a
anyascii @ https://files.pythonhosted.org/packages/39/f6/7c1e3a2a54f18b67c5bd092c25ac7327083d4b3b15731b98a9c193df2db9/anyascii-0.3.1-py3-none-any.whl#sha256=8707d3185017435933360462a65e2c70a4818490745804f38a5ca55e59eb56a0
asgiref @ https://files.pythonhosted.org/packages/af/6d/ea3a5c3027c3f14b0321cd4f7e594c776ebe64e4b927432ca6917512a4f7/asgiref-3.5.2-py3-none-any.whl#sha256=1d2880b792ae8757289136f1db2b7b99100ce959b2aa57fd69dab783d05afac4
async-timeout @ https://files.pythonhosted.org/packages/d6/c1/8991e7c5385b897b8c020cdaad718c5b087a6626d1d11a23e1ea87e325a7/async_timeout-4.0.2-py3-none-any.whl#sha256=8ca1e4fcf50d07413d66d1a5e416e42cfdf5851c981d679a09851a6853383b3c
attrs @ https://files.pythonhosted.org/packages/f2/bc/d817287d1aa01878af07c19505fafd1165cd6a119e9d0821ca1d1c20312d/attrs-22.1.0-py2.py3-none-any.whl#sha256=86efa402f67bf2df34f51a335487cf46b1ec130d02b8d39fd248abfd30da551c
backports.zoneinfo @ https://files.pythonhosted.org/packages/1a/ab/3e941e3fcf1b7d3ab3d0233194d99d6a0ed6b24f8f956fc81e47edc8c079/backports.zoneinfo-0.2.1-cp38-cp38-manylinux1_x86_64.whl#sha256=7b0a64cda4145548fed9efc10322770f929b944ce5cee6c0dfe0c87bf4c0c8c9
beautifulsoup4 @ https://files.pythonhosted.org/packages/d1/41/e6495bd7d3781cee623ce23ea6ac73282a373088fcd0ddc809a047b18eae/beautifulsoup4-4.9.3-py3-none-any.whl#sha256=fff47e031e34ec82bf17e00da8f592fe7de69aeea38be00523c04623c04fb666
CacheControl==0.12.11
cachy==0.3.0
certifi @ https://files.pythonhosted.org/packages/1d/38/fa96a426e0c0e68aabc68e896584b83ad1eec779265a028e156ce509630e/certifi-2022.9.24-py3-none-any.whl#sha256=90c1a32f1d68f940488354e36370f6cca89f0f106db09518524c88d6ed83f382
cffi==1.15.1
charset-normalizer @ https://files.pythonhosted.org/packages/db/51/a507c856293ab05cdc1db77ff4bc1268ddd39f29e7dc4919aa497f0adbec/charset_normalizer-2.1.1-py3-none-any.whl#sha256=83e9a75d1911279afd89352c68b45348559d1fc0506b054b346651b5e7fee29f
cleo==0.8.1
click @ https://files.pythonhosted.org/packages/c2/f1/df59e28c642d583f7dacffb1e0965d0e00b218e0186d7858ac5233dce840/click-8.1.3-py3-none-any.whl#sha256=bb4d8133cb15a609f44e8213d9b391b0809795062913b383c62be0ee95b1db48
clikit==0.6.2
coderedcms @ https://files.pythonhosted.org/packages/92/ab/40cec41594f2db0fd8e7defa593fe9322be5cdbfbc2303dde8108da1d7fb/coderedcms-1.0.1-py3-none-any.whl#sha256=e74173403b249a32fe13a19892caeb4c7dab9585d218656df101da980fd0e5ba
crashtest==0.3.1
cryptography==37.0.4
debugpy @ https://files.pythonhosted.org/packages/d2/e3/d0531ee73216d553d717bf4ac51dff297f89054619fa69db61eef028a07f/debugpy-1.6.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl#sha256=daadab4403427abd090eccb38d8901afd8b393e01fd243048fab3f1d7132abb4
decorator @ https://files.pythonhosted.org/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl#sha256=b8c3f85900b9dc423225913c5aace94729fe1fa9763b38939a95226f02d37186
distlib==0.3.5
Django @ https://files.pythonhosted.org/packages/e1/d0/d90528978da16288d470bb423abad307ed7ae724090132ff6bf67d6a5579/Django-4.0.8-py3-none-any.whl#sha256=27cb08fa6458c1eff8b97c4c2d03774646fb26feeaa4587dca10c49e6d4fc6a3
django-bootstrap5 @ https://files.pythonhosted.org/packages/88/df/27f372ef3308661455996dba5364e1a031f1a2e9ecbc768e204f9dd862a9/django_bootstrap5-21.3-py3-none-any.whl#sha256=c7a686420aa98692f15bd16e61a90dc6a3607e441a4dea37af840b83d4820cac
django-eventtools @ https://files.pythonhosted.org/packages/08/c3/d656a4f8c4d9de9ccb870fac547917c91449ab9f3eece01f29872974b993/django_eventtools-1.0.3-py3-none-any.whl#sha256=ade785536f9bc8e7ae939b35c2637fb2c62341ae51cb7873bf1a25e044052a47
django-filter @ https://files.pythonhosted.org/packages/37/90/8fbf530e14dbcaf502cd80078cbae9e4f805f20888973488ebe8480c3c28/django_filter-21.1-py3-none-any.whl#sha256=f4a6737a30104c98d2e2a5fb93043f36dd7978e0c7ddc92f5998e85433ea5063
django-modelcluster @ https://files.pythonhosted.org/packages/70/ff/e3d6894dc8b5a0ef8c6bde7a88693af257936df11480f33d646b73bb92e1/django_modelcluster-6.0-py2.py3-none-any.whl#sha256=4ae46f86c43702020f24f212222eef0a2588df937bbb523a5447da247b5fb130
django-permissionedforms @ https://files.pythonhosted.org/packages/e6/5b/216157ff053f955b15b9dcdc13bfb6e406666445164fee9e332e141be96d/django_permissionedforms-0.1-py2.py3-none-any.whl#sha256=d341a961a27cc77fde8cc42141c6ab55cc1f0cb886963cc2d6967b9674fa47d6
django-sendmail-backend==0.1.2
django-taggit @ https://files.pythonhosted.org/packages/8f/64/6ca8b92c6cebe43956d27b9c5b7f27cd7e2f04a9407a488f05cd39bf96c7/django_taggit-2.1.0-py3-none-any.whl#sha256=61547a23fc99967c9304107414a09e662b459f4163dbbae32e60b8ba40c34d05
django-treebeard @ https://files.pythonhosted.org/packages/a4/a7/a0359f322d9e843514d95577ee8e64c1662bc4f7764a4d7acc9a9fd66a68/django_treebeard-4.5.1-py3-none-any.whl#sha256=7c2b1cdb1e9b46d595825186064a1228bc4d00dbbc186db5b0b9412357fba91c
djangorestframework @ https://files.pythonhosted.org/packages/ff/4b/3b46c0914ba4b7546a758c35fdfa8e7f017fcbe7f23c878239e93623337a/djangorestframework-3.14.0-py3-none-any.whl#sha256=eb63f58c9f218e1a7d064d17a70751f528ed4e1d35547fdade9aaf4cd103fd08
draftjs-exporter @ https://files.pythonhosted.org/packages/43/21/5ecec14572c86eed3173b8cd8ece268ec20be2faa4ead09669531739d31e/draftjs_exporter-2.1.7-py3-none-any.whl#sha256=d415a9964690a2cddb66a31ef32dd46c277e9b80434b94e39e3043188ed83e33
et-xmlfile @ https://files.pythonhosted.org/packages/96/c2/3dd434b0108730014f1b96fd286040dc3bcb70066346f7e01ec2ac95865f/et_xmlfile-1.1.0-py3-none-any.whl#sha256=a2ba85d1d6a74ef63837eed693bcb89c3f752169b0e3e7ae5b16ca5e1b3deada
filelock==3.7.1
Flask @ https://files.pythonhosted.org/packages/0f/43/15f4f9ab225b0b25352412e8daa3d0e3d135fcf5e127070c74c3632c8b4c/Flask-2.2.2-py3-none-any.whl#sha256=b9c46cc36662a7949f34b52d8ec7bb59c0d74ba08ba6cb9ce9adc1d8676d9526
frozenlist @ https://files.pythonhosted.org/packages/29/ec/5715f872eac10ba488a389f0f2680dafa94f115b823b3ed1cdea31026297/frozenlist-1.3.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=42719a8bd3792744c9b523674b752091a7962d0d2d117f0b417a3eba97d1164b
future==0.18.2
geocoder @ https://files.pythonhosted.org/packages/4f/6b/13166c909ad2f2d76b929a4227c952630ebaf0d729f6317eb09cbceccbab/geocoder-1.38.1-py2.py3-none-any.whl#sha256=a733e1dfbce3f4e1a526cac03aadcedb8ed1239cf55bd7f3a23c60075121a834
html5lib==1.1
icalendar @ https://files.pythonhosted.org/packages/af/fb/e28fbf012fba43501551cd8b528380dbf6523e21952a60935bb99c7c45e9/icalendar-4.1.0-py2.py3-none-any.whl#sha256=129304fdbad4169acc635d08b658ca22ba449b5b22b5157c3774626bc60072db
idna @ https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl#sha256=90b77e79eaa3eba6de819a0c442c0b4ceefc341a7a2ab77d7562bf49f425c5c2
importlib-metadata @ https://files.pythonhosted.org/packages/b5/64/ef29a63cf08f047bb7fb22ab0f1f774b87eed0bb46d067a5a524798a4af8/importlib_metadata-5.0.0-py3-none-any.whl#sha256=ddb0e35065e8938f867ed4928d0ae5bf2a53b7773871bfe6bcc7e4fcdc7dea43
itsdangerous @ https://files.pythonhosted.org/packages/68/5f/447e04e828f47465eeab35b5d408b7ebaaaee207f48b7136c5a7267a30ae/itsdangerous-2.1.2-py3-none-any.whl#sha256=2c2349112351b88699d8d4b6b075022c0808887cb7ad10069318a8b0bc88db44
jedi @ https://files.pythonhosted.org/packages/b3/0e/836f12ec50075161e365131f13f5758451645af75c2becf61c6351ecec39/jedi-0.18.1-py2.py3-none-any.whl#sha256=637c9635fcf47945ceb91cd7f320234a7be540ded6f3e99a50cb6febdfd1ba8d
jeepney==0.8.0
Jinja2 @ https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl#sha256=6088930bfe239f0e6710546ab9c19c9ef35e29792895fed6e6e31a023a182a61
keyring==23.7.0
l18n @ https://files.pythonhosted.org/packages/6c/e7/dfa82d0bb2b314950e457a755463b429090127ffc0ab9d8d14ef4563ad44/l18n-2021.3-py3-none-any.whl#sha256=78495d1df95b6f7dcc694d1ba8994df709c463a1cbac1bf016e1b9a5ce7280b9
lockfile==0.12.2
MarkupSafe @ https://files.pythonhosted.org/packages/fd/f4/524d2e8f5a3727cf309c2b7df7c732038375322df1376c9e9ef3aa92fcaf/MarkupSafe-2.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=4b9fe39a2ccc108a4accc2676e77da025ce383c108593d65cc909add5c3bd601
msgpack==1.0.4
multidict @ https://files.pythonhosted.org/packages/8f/39/a7e04961b4c00d68aba337e3fdef9fd4f666dcd98f41725067a1de5d3399/multidict-6.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=684133b1e1fe91eda8fa7447f137c9490a064c6b7f392aa857bba83a28cfb693
numpy @ https://files.pythonhosted.org/packages/d6/e2/bed33bdbf513cd6d3fcb4377792ef1b8aad941da542a191e1e2a98c6621f/numpy-1.23.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=efd9d3abe5774404becdb0748178b48a218f1d8c44e0375475732211ea47c67e
openpyxl @ https://files.pythonhosted.org/packages/7b/60/9afac4fd6feee0ac09339de4101ee452ea643d26e9ce44c7708a0023f503/openpyxl-3.0.10-py2.py3-none-any.whl#sha256=0ab6d25d01799f97a9464630abacbb34aafecdcaa0ef3cba6d6b3499867d0355
packaging @ https://files.pythonhosted.org/packages/05/8e/8de486cbd03baba4deef4142bd643a3e7bbe954a784dc1bb17142572d127/packaging-21.3-py3-none-any.whl#sha256=ef103e05f519cdc783ae24ea4e2e0f508a9c99b2d4969652eed6a2e1ea5bd522
parso @ https://files.pythonhosted.org/packages/05/63/8011bd08a4111858f79d2b09aad86638490d62fbf881c44e434a6dfca87b/parso-0.8.3-py2.py3-none-any.whl#sha256=c001d4636cd3aecdaf33cbb40aebb59b094be2a74c556778ef5576c175e19e75
pastel==0.2.1
pexpect==4.8.0
Pillow @ https://files.pythonhosted.org/packages/d8/80/ff6b6ae88982f73d050907dc2c307f387f6a04ce2ca7230ef3a568fbccac/Pillow-9.2.0-cp38-cp38-manylinux_2_28_x86_64.whl#sha256=bc431b065722a5ad1dfb4df354fb9333b7a582a5ee39a90e6ffff688d72f27a1
pkginfo==1.8.3
platformdirs==2.5.2
pluggy @ https://files.pythonhosted.org/packages/9e/01/f38e2ff29715251cf25532b9082a1589ab7e4f571ced434f98d0139336dc/pluggy-1.0.0-py2.py3-none-any.whl#sha256=74134bbf457f031a36d68416e1509f34bd5ccc019f0bcc952c7b909d06b37bd3
poetry==1.1.14
poetry-core==1.0.8
psycopg2-binary @ https://files.pythonhosted.org/packages/20/06/4581d1d6e35f2290319501708658208be0e57549b03ac733926a722d47d1/psycopg2_binary-2.9.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=dc85b3777068ed30aff8242be2813038a929f2084f69e43ef869daddae50f6ee
ptyprocess==0.7.0
pycparser==2.21
pyflakes @ https://files.pythonhosted.org/packages/dc/13/63178f59f74e53acc2165aee4b002619a3cfa7eeaeac989a9eb41edf364e/pyflakes-2.5.0-py2.py3-none-any.whl#sha256=4579f67d887f804e67edb544428f264b7b24f435b263c4614f384135cea553d2
pylev==1.4.0
pyparsing @ https://files.pythonhosted.org/packages/6c/10/a7d0fa5baea8fe7b50f448ab742f26f52b80bfca85ac2be9d35cdd9a3246/pyparsing-3.0.9-py3-none-any.whl#sha256=5026bae9a10eeaefb61dab2f09052b9f4307d44aee4eda64b309723d8d206bbc
python-dateutil @ https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl#sha256=961d03dc3453ebbc59dbdea9e4e11c5651520a876d0f4db161e8674aae935da9
python-lsp-jsonrpc @ https://files.pythonhosted.org/packages/06/ee/754bfd5f6bfe7162c10d3ecb0aeef6f882f91d3231596c83f761a75efd0b/python_lsp_jsonrpc-1.0.0-py3-none-any.whl#sha256=079b143be64b0a378bdb21dff5e28a8c1393fe7e8a654ef068322d754e545fc7
pytoolconfig @ https://files.pythonhosted.org/packages/26/15/e21a7c063c29c0b782be090df589b25fdc62ea3b5e5687a94a217851944e/pytoolconfig-1.2.2-py3-none-any.whl#sha256=825d97b052e58b609c2684b04efeb543075588d33a4916a6dc2ae39676458c7d
pytz @ https://files.pythonhosted.org/packages/b5/d7/91fd8911d22e7fac794803095dd192bf1ebd70c7603272085230d915e738/pytz-2022.5-py2.py3-none-any.whl#sha256=335ab46900b1465e714b4fda4963d87363264eb662aab5e65da039c25f1f5b22
ratelim @ https://files.pythonhosted.org/packages/f2/98/7e6d147fd16a10a5f821db6e25f192265d6ecca3d82957a4fdd592cad49c/ratelim-0.1.6-py2.py3-none-any.whl#sha256=e1a7dd39e6b552b7cc7f52169cd66cdb826a1a30198e355d7016012987c9ad08
replit @ https://files.pythonhosted.org/packages/bc/c7/6937037f3152a26917c80eadd4729a63175afe89241e43451d8588bdb130/replit-3.2.4-py3-none-any.whl#sha256=4fa5895e1e090ba23c179641bc88ab0486d1bea696515aa3147fce55733e29e1
replit-python-lsp-server @ https://files.pythonhosted.org/packages/09/42/44ff903505cefa2b2d06fcc164ddff74510eece259e30da6a0c2c68976c8/replit_python_lsp_server-1.15.9-py3-none-any.whl#sha256=205faf150008be7d3da2ac16fc178c833d22835e24841cb82b666443a6b28bef
requests==2.28.1
requests-toolbelt==0.9.1
rope @ https://files.pythonhosted.org/packages/08/81/205ef66c8a129a7b87cbdadf59f2dbc2bbad24c6073d9e393fb0e2aa7d78/rope-1.3.0-py3-none-any.whl#sha256=f0c82bd7167c2926339c6f0d9ecf7c93d6866cbe380c78639fa1bc4ac037c097
SecretStorage==3.3.2
shellingham==1.4.0
six==1.16.0
soupsieve @ https://files.pythonhosted.org/packages/16/e3/4ad79882b92617e3a4a0df1960d6bce08edfb637737ac5c3f3ba29022e25/soupsieve-2.3.2.post1-py3-none-any.whl#sha256=3b2503d3c7084a42b1ebd08116e5f81aadfaea95863628c80a3b774a11b7c759
sqlparse @ https://files.pythonhosted.org/packages/97/d3/31dd2c3e48fc2060819f4acb0686248250a0f2326356306b38a42e059144/sqlparse-0.4.3-py3-none-any.whl#sha256=0323c0ec29cd52bceabc1b4d9d579e311f3e4961b98d174201d5622a23b85e34
tablib @ https://files.pythonhosted.org/packages/41/62/9771bc91ee9e9faa8f00caefd51f77d348cc72f910a96fdd5e2a4cc28ac3/tablib-3.2.1-py3-none-any.whl#sha256=870d7e688f738531a14937a055e8bba404fbc388e77d4d500b2c904075d1019c
telepath @ https://files.pythonhosted.org/packages/0a/eb/ec216110ddfe742c931d9fe84047a89add72c2aa913db31f0348bb16c2de/telepath-0.3-py35-none-any.whl#sha256=fbdbc6bdd9a4a5c2b230caae242fa6ba4994c9dbcfd780df9be63f2966feb034
toml @ https://files.pythonhosted.org/packages/44/6f/7120676b6d73228c96e17f1f794d8ab046fc910d781c8d151120c3f1569e/toml-0.10.2-py2.py3-none-any.whl#sha256=806143ae5bfb6a3c6e736a764057db0e6a0e05e338b5630894a5f779cabb4f9b
tomli @ https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl#sha256=939de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc
tomlkit==0.11.1
typing-extensions @ https://files.pythonhosted.org/packages/74/60/18783336cc7fcdd95dae91d73477830aa53f5d3181ae4fe20491d7fc3199/typing_extensions-3.10.0.2-py3-none-any.whl#sha256=f1d25edafde516b146ecd0613dabcc61409817af4766fbbcfb8d1ad4ec441a34
ujson @ https://files.pythonhosted.org/packages/0a/ac/db3e3b1938729234d2c02ae0111922e5c79af4ddc41bde39f7b4bd2f8aba/ujson-5.5.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=a7d12f2d2df195c8c4e49d2cdbad640353a856c62ca2c624d8b47aa33b65a2a2
urllib3 @ https://files.pythonhosted.org/packages/6f/de/5be2e3eed8426f871b170663333a0f627fc2924cc386cd41be065e7ea870/urllib3-1.26.12-py2.py3-none-any.whl#sha256=b930dd878d5a8afb066a637fbb35144fe7901e3b209d1cd4f524bd0e9deee997
virtualenv==20.16.2
wagtail @ https://files.pythonhosted.org/packages/f6/63/26120d529b869b639142bad73f19d0cf340e57e13969558cfdb5f4fdd870/wagtail-3.0.3-py3-none-any.whl#sha256=111ed9a0a6ff26d5d881d52deb4bf52b627d79a53c43829611752dbb68a9192f
wagtail-cache @ https://files.pythonhosted.org/packages/68/92/8c30e17ffa562e6ecfd4ccc3b63c4442f9a693331d1f38f3fbb2075dc3fb/wagtail_cache-2.2.0-py3-none-any.whl#sha256=a231bc3941eb3ce3e8c73b9aea5d9a54e2f580009a0c87bf86ac59a6545a9609
wagtail-seo @ https://files.pythonhosted.org/packages/2c/d3/5a22e7079d145cd5f0c5b920a855d805080c175d861b03a289e2ec79afaf/wagtail_seo-2.3.0-py3-none-any.whl#sha256=052c1cd56f13ad04ff8dd37c3937085f8f79677241e30ef5900a06c596c283c6
webencodings==0.5.1
Werkzeug @ https://files.pythonhosted.org/packages/c8/27/be6ddbcf60115305205de79c29004a0c6bc53cec814f733467b1bb89386d/Werkzeug-2.2.2-py3-none-any.whl#sha256=f979ab81f58d7318e064e99c4506445d60135ac5cd2e177a2de0089bfd4c9bd5
whatthepatch @ https://files.pythonhosted.org/packages/fe/31/bf06fa31436e8118447bed0a428a1279d1164ebdc2d8866666033ab03ca8/whatthepatch-1.0.2-py2.py3-none-any.whl#sha256=6d920d6c328eda006f12ec05bc9eadb405957b18460520db195f9a21eb3336e1
Willow @ https://files.pythonhosted.org/packages/b5/bb/e654a03c8224b06f9e12381cd0c67028f460e625df55711f7ded30afcaf1/Willow-1.4.1-py2.py3-none-any.whl#sha256=fc4042696d090e75aef922fa1ed26d483c764f005b36cf523cf7c34e69d5dd7a
xlrd @ https://files.pythonhosted.org/packages/a6/0c/c2a72d51fe56e08a08acc85d13013558a2d793028ae7385448a6ccdfae64/xlrd-2.0.1-py2.py3-none-any.whl#sha256=6a33ee89877bd9abc1158129f6e94be74e2679636b8a205b43b85206c3f0bbdd
XlsxWriter @ https://files.pythonhosted.org/packages/ef/95/30f6ee57f10232e2055a85c3e4c8db7d38ab5f1349b6cdced85cb8acd5e6/XlsxWriter-3.0.3-py3-none-any.whl#sha256=df0aefe5137478d206847eccf9f114715e42aaea077e6a48d0e8a2152e983010
xlwt @ https://files.pythonhosted.org/packages/44/48/def306413b25c3d01753603b1a222a011b8621aed27cd7f89cbc27e6b0f4/xlwt-1.3.0-py2.py3-none-any.whl#sha256=a082260524678ba48a297d922cc385f58278b8aa68741596a87de01a9c628b2e
yapf @ https://files.pythonhosted.org/packages/47/88/843c2e68f18a5879b4fbf37cb99fbabe1ffc4343b2e63191c8462235c008/yapf-0.32.0-py2.py3-none-any.whl#sha256=8fea849025584e486fd06d6ba2bed717f396080fd3cc236ba10cb97c4c51cf32
yarl @ https://files.pythonhosted.org/packages/dd/cf/5e7d506b9b5add77548252d6938380e08caf59ba808ac3cf0f0635629d1a/yarl-1.8.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=ea513a25976d21733bff523e0ca836ef1679630ef4ad22d46987d04b372d57fc
zipp==3.8.1

**Comment by keepexploring** [comment]
Thanks so much for your help @vsalvino

**Comment by vsalvino** [comment]
Closing. If anyone can replicate this issue on a fresh install, please re-open with more info.
