### ISSUE TITLE
Webp format and Linkedin cards

### ISSUE THREAD

**Issue by ma00** [coderedcorp/coderedcms#529]
#### Describe the bug
If you post a url with a .webp cover image on linkedin, the image card won't show because the format is not supported.

#### Expected behavior
Is it possible to get linkedin bot fetch a .jpeg or .png image while still showing the .webp image to regular users?

**Comment by vsalvino** [comment]
Thanks for reporting. I guess we may have been a bit too aggressive with the webp implementation. As a workaround, you can set the OpenGraph image in the SEO tab for the page. This should render the image in its original format in the opengraph meta tags.

**Comment by ma00** [comment]
thanks for the reply. Unfortunately linkedin doesn't see the OG image

**Comment by vsalvino** [comment]
So the issue here is that I think you are uploading the image to Wagtail in webp format. For SEO purposes, we do not transform the image it is served directly in original format. Can you try uploading it to Wagtail in JPG or PNG format?

**Comment by ma00** [comment]
Images are uploaded in JPG format and converted with these settings:

`WAGTAILIMAGES_FORMAT_CONVERSIONS = {
    'tiff': 'webp',
    'jpeg': 'webp',
    'bmp': 'webp',
    'png': 'webp',
    'webp': 'webp',
}`

**Comment by vsalvino** [comment]
Ok, that is the problem. You are forcibly converting all file types to webp. I would recommend removing the `WAGTAILIMAGES_FORMAT_CONVERSIONS` setting. CRX will automatically use webp in places where it is acceptable.

**Comment by ma00** [comment]
I removed the lines and now everything started working again, thanks for your help!
