### ISSUE TITLE
Carousel doesn't show child pages of a page with latest pages

### ISSUE THREAD

**Issue by KingWaffleIII** [coderedcorp/coderedcms#530]
The [Wagtail CRX wiki on carousels](https://docs.coderedcorp.com/wagtail-crx/features/snippets/carousels.html#usage) says:
> You define your carousels in the Snippets > Carousel section of the admin. Once defined, any page with a body streamfield can show that carousel by selecting it with a carousel block.

So I did just that in my Wagtail admin, I made a Carousel snippet which should preview some pages. However, when I edit my home page (which should have a body streamfield), I only get the options for a hero unit, card grid, etc. Am I missing something really simple here or do I have to enable something? 

Adding a navbar and footer worked fine since I could add these in CRX settings in the admin.

**Comment by vsalvino** [comment]
To add a carousel from our default body setup, you will need to select *Responsive Grid Row > Column > Carousel*.

You can also access the Responsive Grid Row within a Hero Unit block.

**Comment by KingWaffleIII** [comment]
Hello,
Many thanks for the help - I was able to add the carousel now.
However, my carousel is designed to show the latest content from my news page so I configured it to show the `latest pages` from the news page's child pages. However, once I added the carousel, I only see the following:
![image](https://user-images.githubusercontent.com/43790097/192625131-2f95b017-0643-4d34-a139-fe1caae0a9c8.png)
If I choose the carousel to show an image instead, this works fine?

**Comment by vsalvino** [comment]
When creating the carousel, you have to add slides. I'm guessing you added the content of the first slide to be "latest pages". This *should* work (assuming your news page and its child pages are all published).

However, it might not work as you expect. It will not generate a new slide for each article. It will show all of the articles on the first slide.

To help debug, can you make sure your news page and its child pages are published. Then inspect the source of the carousel screenshotted above. See if there is any indication of those pages in that slide. It is possible they may not be visible due to CSS.

**Comment by KingWaffleIII** [comment]
Yep, you're right - it is a CSS issue. Upon adding a background image, the text is now viewable.
You're also right in that the carousel doesn't work how I wanted it to so I guess I'm not going to use that.

At any rate, thank you for your help!

**Comment by vsalvino** [comment]
I would recommend creating a custom html template for the LatestPages block (there are currently a couple built-in ones under Advanced Settings). Then you can make your custom template render as a bootstrap carousel for each page. This would require some development.

The process for adding a custom template is not perfect yet, but all you need to do is add `CRX_FRONTEND_TEMPLATES_BLOCKS` to your Django settings. I'd recommend copying our default one, and adding your custom files where necessary.

https://github.com/coderedcorp/coderedcms/blob/aec431be55a8a04f179ac4e7ec88d469c2856856/coderedcms/settings.py#L146
