### ISSUE TITLE
Image upload error 

### ISSUE THREAD

**Issue by joeblinx39** [coderedcorp/coderedcms#531]
#### Describe the bug
Displaying KeyError syntax whenever I upload an image 

#### Steps to reproduce
1. Go to 'edit home page'
2. Click on 'add image to hero unit'
3. See error

#### Expected behavior
It is meant to accept the image and display it

**Comment by vsalvino** [comment]
Please post the stack trace. Be sure to set DEBUG=True in your settings so that Django will produce a full stack trace.

It will be impossible for us to help without more info.

**Comment by joeblinx39** [comment]
I was able to fix it by going to the base.html and admin.html templates files in the coderedcms folder the issue was that in the image statement the format was set to webp which was conflicting the formats I was uploading

**Comment by vsalvino** [comment]
Hmm... wagtail should convert whatever image you upload into webp, via the renditions. What kind of image were you uploading? If possible, could you link it here so we can try to replicate?

**Comment by joeblinx39** [comment]
I tried uploading a .jpg image but it didn't work then I used an online
image converter to convert the jpg image to webp image but when I tried to
upload that image it said that image is corrupted
