### ISSUE TITLE
Docs display oddly at certain screen widths.

### ISSUE THREAD

**Issue by Zsvoboda87** [coderedcorp/coderedcms#538]
#### Describe the bug
While using the docs I had my browser set to somewhere around 1000px wide and notice that the docs do not display as expected.  At first I thought there was no content, however it shows up below the menu.

![image](https://user-images.githubusercontent.com/93960196/203095626-c73782a8-4af0-498d-a42c-147d54d5be0f.png)

#### Steps to reproduce
1. Go to 'https://docs.coderedcorp.com/wagtail-crx/features/blocks/contentblocks/card.html'
Set browser width between 991px and 1064px 

#### Expected behavior
I would expect it to behave like it does for a smaller or larger pixel count.

**Comment by vsalvino** [comment]
Please file this bug at: https://github.com/wagtail/sphinx_wagtail_theme

**Comment by vsalvino** [comment]
I'm wondering if they fixed that, as I'm not seeing it on the wagtail docs. Can you try pip-installing the latest version of `sphinx_wagtail_theme`, and re-build our docs, and see if it occurs locally?

**Comment by Zsvoboda87** [comment]
Yeah I can do that,  I’m using the edge.  Probably should have mentioned that.Zachary ***@***.*** Nov 21, 2022, at 10:56 AM, Vince Salvino ***@***.***> wrote:﻿
I'm wondering if they fixed that, as I'm not seeing it on the wagtail docs. Can you try pip-installing the latest version of sphinx_wagtail_theme, and re-build our docs, and see if it occurs locally?

**Comment by Zsvoboda87** [comment]
After testing both docs, I believe this is happening because there is 5 tiers.  It doesn't seem to happen anywhere else in these docs and the wagtail docs never have 5 sub categories.

![image](https://user-images.githubusercontent.com/93960196/203103667-e88b2f0d-ffa7-47a2-a09e-7033abae677c.png)

**Comment by vsalvino** [comment]
Closing this as the structure of the docs has changed. Feel free to re-open if new information arises.
