### ISSUE TITLE
Bug related to wagtail-seo

### ISSUE THREAD

**Issue by vorletzter** [coderedcorp/coderedcms#552]
I tried implementing Structured Data for an EventPage using wagtail-seo. 

As far as i understand the CRX Codebase, the Structured Data is supposed to be processed and renderd by [Line 62 in the event_page.html](https://github.com/coderedcorp/coderedcms/blob/5c28e730acaf8aaceb7b12b943853c78e5f60944/coderedcms/templates/coderedcms/pages/event_page.html#L62) Template. 

But is  _{% block struct_seo_extra %}_ ever processed? It is defined in _wagtailseo/struct_data.html_ which gets included  in the _base Template_. But as far as i  know, Django does not process blocks in included files. At least this is my current guess, why I could not get any Structured Data to render.

According to the wagtail-seo documentation {{ self.my_struct_recipe_json }} should be put directly in the template. 
Doing so in CRX  raises an AttributeError ( 'tuple' object has no attribute 'start' ) in [Line 832 in models/page_models.py](https://github.com/coderedcorp/coderedcms/blob/5c28e730acaf8aaceb7b12b943853c78e5f60944/coderedcms/models/page_models.py#L832) 

I figure because self.most_recent_occurrence returns a Tuple (0 = start, 1=end, 2=Reference to the Model).
So 
"startDate": next_occ.start
should be
"startDate": next_occ[0],
or 
"startDate": next_occ[2].start,

Am i missing something crucial here? 
Or did i stumble on two bugs? 

Django==4.0.8
coderedcms==1.0.1
wagtail-seo==2.3.0

**Comment by vorletzter** [comment]
Found another somehow related Issue with django-eventtools.
[Line 820 in page_models.py](https://github.com/coderedcorp/coderedcms/blob/5c28e730acaf8aaceb7b12b943853c78e5f60944/coderedcms/models/page_models.py#L820) e.next_occurrences returns a None if there are only Occurrences in the past, resulting in a NoneTypes not subscriptable error. Breaking the Previews. 

A quick and dirty fix for the Preview Exception
```
        except AttributeError:
            # Triggers when a preview is initiated on an
            # EventPage because it uses a FakeQuerySet object
            # and 'FakeQuerySet' object has no attribute 'all_occurrences'
            # Here we manually compute the next_occurrence

            aoc = []
            for a in self.occurrences.all(): 
                aoc += [instance for instance in a.all_occurrences()]

            if len(aoc) > 0:
                return sorted(aoc, key=lambda tup: tup[0])[-1]

            return None
```
Or one could just check if  occurrences contains None and abort the calculation if speed for such an edgecase might be an Issue..

```
        except AttributeError:
            # Triggers when a preview is initiated on an
            # EventPage because it uses a FakeQuerySet object.
            # Here we manually compute the next_occurrence
            occurrences = [e.next_occurrence() for e in self.occurrences.all()]
            if None in occurrences:
              return None
            if occurrences:
                return sorted(occurrences, key=lambda tup: tup[0])[0]
```

**Comment by vsalvino** [comment]
Thanks for reporting and doing the leg work to track it down. I do think we have a bug of sorts, related to the events. We are seeing a similar error on another CRX site.
