### ISSUE TITLE
Seemingly outdated documentation

### ISSUE THREAD

**Issue by apetryla** [coderedcorp/coderedcms#561]
Hello, 

was searching for `QuoteBlock` under `coderedcms.content_blocks` as shown in the [docs](https://docs.coderedcorp.com/wagtail-crx/features/blocks/index.html). Found it in `coderedcms.blocks.html_blocks`. Do this docs need to be updated?

**Comment by apetryla** [comment]
Context: I'm adding `coderedcms` to an existing project. I can't find any documentation on how to do it. Some challenges I faced on the way:

1. had to install `wagtail-seo` and add `wagtailseo` to the `INSTALLED_APPS` in django settings.
2. Was getting `NoReverseMatch at /cms/settings/coderedcms/layoutsettings/2/ Reverse for 'import_index' not found. 'import_index' is not a valid view function or pattern name.` error. Solved by adding `from coderedcms.admin_urls import urlpatterns as coderedcms_urls` to my project's `urls.py` and including `*coderedcms_urls,` in the `urlpatterns`.

Please let me know if I missed any documentation or could do anything better here. :)

**Comment by vsalvino** [comment]
Regarding the QuoteBlock, you can import everything from `coderedcms.blocks`.

See this issue about adding to an existing site: https://github.com/coderedcorp/coderedcms/issues/327
