### ISSUE TITLE
Theme variants not working in sass version

### ISSUE THREAD

**Issue by EnriqueRBT** [coderedcorp/coderedcms#563]
Hi:

I don't know if this is an issue or just normal functioning, but in a a fresh installation with sass option, bootswatch themes doesn`t work ( in Editing-CRX-Settings) .  I have to delete the base.html on website folder, but then I lose customization.

Any hint? Thanks.

**Comment by vsalvino** [comment]
That would be correct. The whole point of sass is that you are customizing the CSS build in code. The `base.html` template that is included in the boilerplate sass project specifically uses your custom built CSS, it does not read that setting.
