### ISSUE TITLE
Missing closing figure tag in quote_block.html

### ISSUE THREAD

**Issue by webvoyant** [coderedcorp/coderedcms#577]
#### Describe the bug
The missing `</figure>` tag in `quote_block.html` causes any custom CSS classes applied to quotes to affect all the following elements on the page.

#### Steps to reproduce
Steps to reproduce the behavior: (I was working on a Blog Article page at the time)
1. While editing a page, place a quote block above a text block with some content in both.
2. At the quote block, click on **Advanced Settings** and add `text-center` as a **Custom CSS Class**.
3. In the preview pane, watch the text in both blocks move to the center.

#### Expected behavior
Only the text in the quote block should center.

#### Additional context
I added the missing tag and it works as expected.
```
{% endif %}
</figure>
{% endblock %}
```

**Comment by vsalvino** [comment]
Thanks for reporting. This would make a great pull request if you're interested in contributing :)
