### ISSUE TITLE
Cards are not equal height

### ISSUE THREAD

**Issue by rosslaird** [coderedcorp/coderedcms#578]
In card grid decks and related page decks, the cards are not equal height (unless the line breaks happen to line up). See the attached example showing the bottom borders of a row of related pages.

Applying ```.h-100``` to each card, or ```$card-height: 100%``` in Sass (as per Bootstrap [docs](https://getbootstrap.com/docs/5.0/components/card/#grid-cards)) will render the cards in equal height. The card grid decks [allow for this](https://github.com/coderedcorp/coderedcms/blob/2983127e087bd8d3c5a8f50cfb94dac8c0b3c5c1/coderedcms/templates/coderedcms/blocks/cardgrid_deck.html#L4) via adding ```h-100``` to the custom CSS field, but the related page cards do not offer that option.

I think most users would want the related page cards to be of equal height as well as the cards of regular card decks. This could be achieved globally by adding ```$card-height: 100%;``` to the SCSS (this is what I will do for now, in my own project). I would volunteer to create a pull request for this, but I'm not sure you want a global solution for all cards (as I do), and I'm not sure where you'd want the code to be (in [custom.scss](https://github.com/coderedcorp/coderedcms/blob/2983127e087bd8d3c5a8f50cfb94dac8c0b3c5c1/coderedcms/project_template/sass/website/static/website/src/custom.scss)?).

Another option would be to specify ```.h-100``` in the template just for related pages, or to add the custom CSS option to related pages.

<img width="1328" alt="example" src="https://github.com/coderedcorp/coderedcms/assets/75513/12e44e9c-d9c0-4d4e-8b2a-dcf77c8fbad5">

**Comment by rosslaird** [comment]
Actually, it looks like ```$card-height: 100%;``` does not actually result in equal-height cards in all situations. I'm not sure what's causing this inconsistency.

**Comment by vsalvino** [comment]
I think adding `.h-100` by default to our new miniview templates `card` would be the ideal result. I'm not sure if that will cause issues when the miniview is singular (i.e. the Page Preview block). This h-100 method does require the card to have a footer I believe, so the "Read more" link might need to be moved to a card footer, which would be fine.

https://getbootstrap.com/docs/5.2/components/card/#grid-cards

**Comment by rosslaird** [comment]
In the first example of equal height cards in the [Bootstrap docs](https://getbootstrap.com/docs/5.2/components/card/#grid-cards) (same link as above), the cards do not have footers (see screenshot). In the second example they do. So, I'm not sure if the footer is actually required to make the cards equal height.

It does not seem that CRX is using the ```.row-cols-*``` classes shown in the [Bootstrap docs](https://getbootstrap.com/docs/5.2/layout/grid/#row-columns) (at least, these classes do not appear in the source code for related pages and latest pages on my site, I couldn't find the string ```row-cols``` anywhere in the repo, and I did not see anything involving these classes after looking at every example of the term ```row``` in the repo). As these classes are shown in every card example in the docs (equal height or otherwise), I wonder if this might be related to the issue at hand?

("Latest Pages" is another place this issue shows up.)

<img width="821" alt="Screenshot 2023-05-27 at 11 14 18 AM" src="https://github.com/coderedcorp/coderedcms/assets/75513/5ad24308-9b14-4800-836c-e47c6617aada">
