### ISSUE TITLE
Navbar logo centered both horizontally and vertically?

### ISSUE THREAD

**Issue by rosslaird** [coderedcorp/coderedcms#605]
I wonder if the vertically centered navbar logo could also be horizontally centered with the rest of the navbar. At the moment, if the logo is large enough to be a visual branding element, quite a bit of white space is created. Here's an example:

<img width="1389" alt="Screenshot 2023-11-19 at 9 03 59 AM" src="https://github.com/coderedcorp/coderedcms/assets/75513/835d4945-03ab-4125-9607-377a5abb79f7">

And here's an example of the kind of approach I have in mind, with the logo and menu items more horizontally centered,  from [The Atlantic](https://www.theatlantic.com/) (if not exactly centred, at least with less white space):

<img width="1389" alt="Screenshot 2023-11-18 at 3 26 28 PM" src="https://github.com/coderedcorp/coderedcms/assets/75513/b73cfb4f-5df5-46bc-a6f6-c188de462fd0">

**Comment by rosslaird** [comment]
It looks like this setting is controlled by a couple of lines of SCSS [code](https://github.com/coderedcorp/coderedcms/blob/fdc7a202d52b926122b8e0e91151d3b5509a2f2c/coderedcms/static/coderedcms/scss/_crx-navbar.scss#L62), so I imagine it's not that difficult to change?

**Comment by rosslaird** [comment]
After some _non-expert_ experimentation, it looks like this can be achieved in the following way:

1. Add `align-items-center` to the `container` div that contains `navbar-brand`:
```
<div class="container align-items-center>
<a class="navbar-brand" href="/">
```

2. Add the following to custom.scss:

```
.crx-navbar-center .navbar-brand img {
height: 135px;  /* desired logo height */
width: auto;  
margin-top: auto;  
margin-bottom: auto;  
}
```
3. Fine-tuning of the logo positioning can be achieved with:
```
 transform: translateY(25%); /* desired logo offset along the Y axis, i.e. vertically */
```
It looks like using `transform` in this way also makes step 1 unnecessary — but may have implications for responsiveness that I'm not seeing.

This solution appears to work but may not be the _best_ solution.

**Comment by rosslaird** [comment]
The method I'm using does cause too much white space between the logo and the top of the page, so I adjusted the logo upward and changed the positioning of the menu and search bar as well:

```
.nav-item, form[role=search] {
  transform: translateY(-100%);
}
```
This gets me exactly what I'm looking for (on large screens). Now I just have to figure out a responsiveness rule to cancel out these adjustments on smaller screens (maybe to hide the logo altogether). Progress, though.

**Comment by vsalvino** [comment]
It's a nice-looking design, but probably not something we'd want to offer directly in CRX, as it could vary greatly from site-to-site based on the size and shape of the logo.

Theming has been on the backburner for quite a while (#44). Although this would be a prime candidate for something that should be handled in a theme, as it would require some custom HTML and CSS.

On every site we build, in practice we end up having to completely do a custom navbar. No surprise here that you're needing to also customize the navbar. The navbar in CRX needs re-thought because the designs vary so much from site-to-site, but we haven't really figured out what the ideal implementation is yet (#56)

**Comment by rosslaird** [comment]
I did look at the discussion about theming before diving into this experiment, and I can see how complex and unpredictable the implementation might be. For now, I'm fine with the solution I've come up with.
