### ISSUE TITLE
Error with generating single .ical

### ISSUE THREAD

**Issue by Sreini** [coderedcorp/coderedcms#612]
https://github.com/coderedcorp/coderedcms/blob/9591169c8ada8119773fc6bd37a9be5618324882/coderedcms/views.py#L142

I'm getting an error message when using the "generate single ical" button:

![image](https://github.com/coderedcorp/coderedcms/assets/36940685/eb405ed6-5276-4e2f-b74c-cefb017278e3)

The values being passed don't seem unreasonable:

![image](https://github.com/coderedcorp/coderedcms/assets/36940685/1da60d6c-d952-4af7-a925-244b021565f0)

But digging a bit deeper, it seems that they are a problem: the code expects a timezone to be generated, but this doesn't seem to be the case: 
![image](https://github.com/coderedcorp/coderedcms/assets/36940685/57b319cd-c050-4230-8cf2-815a9ce48624)

It seems its a problem that the datetime here is "naive" (idk what that means) but for this reason parsing this datetime isn't working well, as the parser expects a timezone.

I am not knowledgeable enough about python to know what the best solution is here, but hopefully someone who does can take the last step and solve this issue for everyone!

**Comment by vsalvino** [comment]
Hello - the error message here means that your event page is missing the start and end times. Can you double check that event in the Wagtail admin and ensure it has start and end datetimes set?

**Comment by vsalvino** [comment]
Glad that worked. I suppose we should update the docs to specify that the calendar only works with time zone support enabled.

**Comment by vsalvino** [comment]
Added docs with 4.1
