### ISSUE TITLE
Support Wagtail 6.0

### ISSUE THREAD

**Issue by rxm7706** [coderedcorp/coderedcms#622]

**Comment by cesar-benjamin** [comment]
hello, is there a date to release 4.0 and wagtail 6 support?

**Comment by rxm7706** [comment]
Hi @vsalvino @jlchilders11 - Do you have an ETA for your 4.0 release and wagtail 6.0 support. 
PR - https://github.com/coderedcorp/coderedcms/pull/624
Thank you and Regards.
