### ISSUE TITLE
Possible typo in coderedcms.forms

### ISSUE THREAD

**Issue by ElectronicRU** [coderedcorp/coderedcms#628]
https://github.com/coderedcorp/coderedcms/blob/main/coderedcms/forms.py#L187

Shouldn't the 'default' here be 'singleline' instead of the untranslated help string?

**Comment by vsalvino** [comment]
I think you are correct. If you can make a test a fix, I'd be happy to merge it. Thanks!

**Comment by ElectronicRU** [comment]
Not sure how to write a DRY test for this. Does this need a testcase?

**Comment by vsalvino** [comment]
Don't need a test for that, it is a small enough fix. Thanks!
