### ISSUE TITLE
Reusable forms

### ISSUE THREAD

**Issue by Aneemes** [coderedcorp/coderedcms#629]
I have been working on a project for a company, which reuires to have forms at the end of multiple pages, sort of like a feedback for a product or article. It would be a really useful addon to create a form and have an option to choose it in some types of pages.

**Comment by TheCodingSheikh** [comment]
you can, create a form page, and in the page you want to display the feedback form, add it as "page preview block" and choose the form page, it'll be displayed in the same page

**Comment by vsalvino** [comment]
Yes, as describe above, you can create your Form page once. Then on any other page on the site, in the streamfield, choose "Page Preview Block". By default it will render the form in that spot in the streamfield.

You can customize the HTML/style of this preview by overriding the `miniview_template` attribute on the FormPage.
