### ISSUE TITLE
Search page empty query

### ISSUE THREAD

**Issue by vsalvino** [coderedcorp/coderedcms#63]
On an empty query, the default behavior is not super user-friendly. If you go to the search page without specifying a query, or try to search with an empty query somehow, it currently shows a search term of "None" or a search term of "" (empty string) and no results found. Ideally with None or empty search query:
* Title would just say "Search"
* "No results found" message would probably be omitted.

These changes should be possible in the search html template.

![image](https://user-images.githubusercontent.com/13453401/50237246-62d4e380-038a-11e9-827f-35f9557a2c1d.png)

**Comment by Ryan-Britnell** [comment]
I'm happy to take this one if it is still open.

**Comment by vsalvino** [comment]
Go for it!
