### ISSUE TITLE
Microsoft 365 SendMail

### ISSUE THREAD

**Issue by softlightMatt** [coderedcorp/coderedcms#667]
Hi,

I'm fairly new to this, but am trying to set up the email service on the live site. I need to email form submissions to a specified email address.

I'm not really sure how to go about this.

Microsoft won't allow/are discontinuing SMTP send, from what I've been able to determine and I'm not sure how to proceed.

I found https://github.com/evyd13/django-o365mail, which looks like it will deal with the authentication, and have (as far as I can tell) configured it correctly, but it's not sending anything from the forms.

Has anyone else come across this, does anyone have any solutions? I really need to get this working and I'm tearing my hair out!

Thanks very much

Matt

**Comment by vsalvino** [comment]
You need an SMTP server to send mail.

I'd recommend either [Mailgun](https://www.mailgun.com/) or [Sendgrid](https://sendgrid.com/en-us), both are affordable and reliable.

Alternatively, if you're hosting your site on [CodeRed Cloud](https://www.codered.cloud/), we do provide SMTP server included, and you don't have to configure anything in your app to send mail, it automatically works out of the box :)  However it is only available on paid plans.

Hope this helps!

**Comment by softlightMatt** [comment]
Thanks for that, would have saved me a lot of time if I'd checked here first!

I'm setting it up using Mailgun, as suggested.

In settings/prod.py I've entered:

EMAIL_BACKEND = 'django_sendmail_backend.backends.EmailBackend'

EMAIL_HOST = 'smtp.eu.mailgun.org'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = '****@***.com'
EMAIL_HOST_PASSWORD = '*****************'
DEFAULT_FROM_EMAIL = '**********@***********.com'

The DEFAULT_FROM_EMAIL is actually set above in the prod.py file, but is the same as that in the CRX Settings on the website..

When I send a form, I'm now getting the response: "Incomplete response received from application".

Port 587 is open on my server, Mailgun is configured correctly, and the host info is correct.

Thanks in advance for your help.

Matt

**Comment by vsalvino** [comment]
You need to switch the `EMAIL_BACKEND` to use SMTP instead of sendmail: https://docs.djangoproject.com/en/5.1/topics/email/#smtp-backend

```python
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
```
