### ISSUE TITLE
Bug in prod.by

### ISSUE THREAD

**Issue by ntbrown** [coderedcorp/coderedcms#69]
In the snippet

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wagtail.contrib.settings.context_processors.settings',
            ],
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]

You can't have both `APP_DIRS` and `loaders` set. `APP_DIRS` should be removed when `prod.py` is being used.

**Comment by vsalvino** [comment]
Fixed in master
