### ISSUE TITLE
Database search backend is too bad

### ISSUE THREAD

**Issue by vsalvino** [coderedcorp/coderedcms#82]
Wagtail's build-in database search backend does not provide good search results in coderedcms due to the fact that it can't search multiple fields on multiple different models, it can only search fixed fields on ALL models or multiple fields per-model. We have some workarounds in coderedcms for this (see [searching docs](https://docs.coderedcorp.com/cms/stable/features/searching.html)), but they are not ideal.

The elasticsearch backend is probably ideal, but adds an extra infrastructure component which is overkill for smaller sites. Similarly, there is a postgres backend but that does not support mysql or sqlite.

I recently discovered https://github.com/wagtail/wagtail-whoosh which would probably solve all of our problem, assuming it is actually portable between all database types. The one trick here is the need to run `update_index` to relfect changes, but we *might* be able to run that on a hook when a new page is published or when the cache is cleared. At any rate, if it does have to be run via cron job, I think cron is an "acceptable" piece of infrastructure moreso than requiring a specific database or elasticsearch.

Alternatively, I would love to write a mysql search backend that takes advantage of powerful full text indexing in mysql - but do not have enough knowledge about search backends to accomplish that in a timely manner. Regardless, I think wagtail-whoosh might be preferable to database-dependent backends.

**Comment by RNCTX** [comment]
Related: the current docs say that Postgres is capable of body text searching, but after starting a test site that started as sqlite an then transitioning to and applying the same migrations to postgres, searches still do not match body text.

Is there another change needed somewhere to enable this?

**Comment by vsalvino** [comment]
You will have to change wagtail's search backend from database (generic) to postgres: https://docs.wagtail.io/en/v2.6.3/reference/contrib/postgres_search.html

**Comment by RNCTX** [comment]
hmm, not working.

I can see in your model that ['body'](https://github.com/coderedcorp/coderedcms/blob/e38c292cadffb206248941f50e88748b685d6b78/coderedcms/models/page_models.py#L634) is appended to the search fields for article page...

```
# Search fields
    search_fields = (
        CoderedPage.search_fields +
        [index.SearchField('body')]
    )
```

But it doesn't work, either on an existing article or a freshly published one.  Body text still doesn't match while title, for example, does.  Do I need to make any changes to the default navbar search form?

**Comment by vsalvino** [comment]
Hmm, it could be a bug in our code potentially. Here is our search view, with the relevant part highlighted when you're not using the database backend:

https://github.com/coderedcorp/coderedcms/blob/e38c292cadffb206248941f50e88748b685d6b78/coderedcms/views.py#L71-L80

I thought that Postgres supported searching subclasses from a parent class, but if that is *not* the case it would be omitting the body. We are calling search on `CoderedPage` which itself does not have a body, but subclasses do have a body.

**Comment by RNCTX** [comment]
Yep, `t=articlepage` worked to match text from an article.

**Comment by vsalvino** [comment]
Ok, two workarounds then: you can use `search_filterable=True`, or `search_db_include=True` (or give up and use elastic search).

Hoping you didn't waste too much time converting to postgres for that feature that didn't exist. We will have to update our search docs now that this is confirmed.

https://docs.coderedcorp.com/cms/stable/features/searching.html#search-fields

**Comment by RNCTX** [comment]
No worries, I was going to switch to postgres anyway.

The second option isn't going to work because as your docs say, `search_db_include` is ignored with postgres as a search backend. The faceting option isn't really a good one to just search blog posts either, since there's no way for the user to get to a set of results to drill down from with the included basic search box.

I think my best compromise until better choices come along in the future is just to hard code articlepage as the model type on the default search form.

**Comment by vsalvino** [comment]
We could very easily enable that for postgres by modifying a couple lines in the view. Just need to remove the `if` check against the database backend. We could maybe change that to check if not elasticsearch.

We had been working under the assumption that the postgres backend was more powerful than it actually is :) We're primarily a MySQL shop so it hasn't come up yet.

https://github.com/coderedcorp/coderedcms/blob/e38c292cadffb206248941f50e88748b685d6b78/coderedcms/views.py#L55

https://github.com/coderedcorp/coderedcms/blob/e38c292cadffb206248941f50e88748b685d6b78/coderedcms/views.py#L61

It would be great if you could submit a pull request since you have a good use-case to test this feature out.

**Comment by RNCTX** [comment]
Will test it out and do so in a few hours, thanks!

**Comment by RNCTX** [comment]
Well, I misspoke in the earlier replies, probably due to having a dev server browser tab open and a live server browser tab open simultaneously and testing the wrong one without noticing.  In the coderedcms page model as-is, explicitly stating the model to search in the string does work for sqlite, but does not work for postgres.

And here's why:

> [wagtail docs on postgres search backend:](https://docs.wagtail.io/en/v2.6.3/reference/contrib/postgres_search.html)
> * When Specifying the fields to search, the index is not used, so it will be slow on huge sites.
> * Still when Specifying the fields to search, you cannot search on a specific method.

So it seems to me the fix that is inclusive of postgres, while adding minimal future maintenance overhead, is to explicitly declare which fields go into the index without any inheritance between the included  default page models, and then in turn for the index to be *absolutely* authoritative in the case of a postgres search config, to go with a new postgres search model since it can't share with the sqlite one anymore.

Docs should probably come with a note in the development guidelines that any new page classes the user might come up with need to follow this convention of explicitly declaring search index fields in the case of postgres without any inheritance, lest their search results be inaccurate/unreliable.

**Comment by vsalvino** [comment]
Have you tried using the DatabaseBackend instead of the Postgres backend? It should be uniform across all database types.

**Comment by RNCTX** [comment]
Same as the postgres backend, specifying a model type doesn't change the search result like it does for sqlite.

**Comment by adminBCI** [comment]
If I use wagtail-whoosh with codered, I get following error if I manage.py update_index

django.db.utils.ProgrammingError: column website_formpage.spam_protection does not exist
LINE 1: ..._golive_at", "website_formpage"."form_expire_at", "website_f...

**Comment by vsalvino** [comment]
Interesting... I have not used wagtail-whoosh yet but have been meaning to try it out.

Could this be the result of missing a migration? Try running (assuming your coderedcms app is called "website"):
```
python manage.py makemigrations website
python manage.py migrate
```

**Comment by adminBCI** [comment]
I fixed it as follows:
`rm website/migrations/000[0-9]_*.py
./manage.py makemigrations
Delete line containing spam_protection in website/migrations/0001_*.py

./manage.py makemigrations
./manage.py migrate`

**Comment by adminBCI** [comment]
Please consider adding support for Haystack. Then I can use any search backend. I am not a fan of Elastic but I might roll out my own search engine later (I have been thinking about it for the past 20yrs)

**Comment by vsalvino** [comment]
Haystack is a good idea, and would actually be a great addition to wagtail, since we are just using the stock wagtail search functionality.

It might be worth cruising the wagtail github issues and the wagtail slack to see if there is any haystack support.

**Comment by vsalvino** [comment]
For anyone still following this, Wagtail 2.15 has totally refactored their search backends. We will obviously need to test this out and integrate it with coderedcms.

https://docs.wagtail.io/en/latest/releases/2.15.html
