### ISSUE TITLE
Add class to the page title in it's html template.

### ISSUE THREAD

**Issue by corysutyak** [coderedcorp/coderedcms#9]
Currently there is no easy way to select a title of a page in the html with css.  We should make a change to add a class to the h1 for the titles to make them easily selectable.

**Comment by vsalvino** [comment]
In a similar vain, I'm wondering if it would be a good idea to add custom predictable CSS class names to all of our default HTML templates. Similar to how wagtail generates CSS classes around blocks.

This would allow quicker customization without the need to create custom templates by coderedcms users.

**Comment by vsalvino** [comment]
Could we consider this closed since the new `content_header` block was added to the web_page template per commit https://github.com/coderedcorp/coderedcms/commit/9b727b609d9d46d06cd0cabb70826d094cc0aa99 ?

**Comment by vsalvino** [comment]
Closing this issue since it seems the page templates are extensible enough for now.
