### ISSUE TITLE
Form help text should be rich

### ISSUE THREAD

**Issue by vsalvino** [coderedcorp/coderedcms#94]
In some cases, it would be beneficial to insert links or minor formatting of the form field help text. This could potentially be a rich text block.

This might introduce concerns such as rendering with django-bootstrap4, or within the form inline panel itself.

**Comment by corysutyak** [comment]
While not a perfect fit, this will be somewhat fixed with #171 You will be able to add a rich text block in between form elements in a stream form.

**Comment by vsalvino** [comment]
Closing this, I think the recommended solution in this case would be to use the new streamforms for more advanced form layout.
